// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/spec/v1/component.proto

package com.secretflow.spec.v1;

/**
 * <pre>
 * The value of an attribute
 * </pre>
 *
 * Protobuf type {@code secretflow.spec.v1.Attribute}
 */
public final class Attribute extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:secretflow.spec.v1.Attribute)
    AttributeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Attribute.newBuilder() to construct.
  private Attribute(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Attribute() {
    s_ = "";
    fs_ = emptyFloatList();
    i64S_ = emptyLongList();
    ss_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    bs_ = emptyBooleanList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Attribute();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_Attribute_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_Attribute_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.secretflow.spec.v1.Attribute.class, com.secretflow.spec.v1.Attribute.Builder.class);
  }

  public static final int F_FIELD_NUMBER = 1;
  private float f_ = 0F;
  /**
   * <pre>
   * FLOAT
   * </pre>
   *
   * <code>float f = 1;</code>
   * @return The f.
   */
  @java.lang.Override
  public float getF() {
    return f_;
  }

  public static final int I64_FIELD_NUMBER = 2;
  private long i64_ = 0L;
  /**
   * <pre>
   * INT
   * NOTE(junfeng): "is" is preserved by Python. Replaced with "i64".
   * </pre>
   *
   * <code>int64 i64 = 2;</code>
   * @return The i64.
   */
  @java.lang.Override
  public long getI64() {
    return i64_;
  }

  public static final int S_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object s_ = "";
  /**
   * <pre>
   * STRING
   * </pre>
   *
   * <code>string s = 3;</code>
   * @return The s.
   */
  @java.lang.Override
  public java.lang.String getS() {
    java.lang.Object ref = s_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      s_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * STRING
   * </pre>
   *
   * <code>string s = 3;</code>
   * @return The bytes for s.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSBytes() {
    java.lang.Object ref = s_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      s_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int B_FIELD_NUMBER = 4;
  private boolean b_ = false;
  /**
   * <pre>
   * BOOL
   * </pre>
   *
   * <code>bool b = 4;</code>
   * @return The b.
   */
  @java.lang.Override
  public boolean getB() {
    return b_;
  }

  public static final int FS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.FloatList fs_;
  /**
   * <pre>
   * FLOATS
   * </pre>
   *
   * <code>repeated float fs = 5;</code>
   * @return A list containing the fs.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getFsList() {
    return fs_;
  }
  /**
   * <pre>
   * FLOATS
   * </pre>
   *
   * <code>repeated float fs = 5;</code>
   * @return The count of fs.
   */
  public int getFsCount() {
    return fs_.size();
  }
  /**
   * <pre>
   * FLOATS
   * </pre>
   *
   * <code>repeated float fs = 5;</code>
   * @param index The index of the element to return.
   * @return The fs at the given index.
   */
  public float getFs(int index) {
    return fs_.getFloat(index);
  }
  private int fsMemoizedSerializedSize = -1;

  public static final int I64S_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList i64S_;
  /**
   * <pre>
   * INTS
   * </pre>
   *
   * <code>repeated int64 i64s = 6;</code>
   * @return A list containing the i64s.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getI64SList() {
    return i64S_;
  }
  /**
   * <pre>
   * INTS
   * </pre>
   *
   * <code>repeated int64 i64s = 6;</code>
   * @return The count of i64s.
   */
  public int getI64SCount() {
    return i64S_.size();
  }
  /**
   * <pre>
   * INTS
   * </pre>
   *
   * <code>repeated int64 i64s = 6;</code>
   * @param index The index of the element to return.
   * @return The i64s at the given index.
   */
  public long getI64S(int index) {
    return i64S_.getLong(index);
  }
  private int i64SMemoizedSerializedSize = -1;

  public static final int SS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList ss_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * STRINGS
   * </pre>
   *
   * <code>repeated string ss = 7;</code>
   * @return A list containing the ss.
   */
  public com.google.protobuf.ProtocolStringList
      getSsList() {
    return ss_;
  }
  /**
   * <pre>
   * STRINGS
   * </pre>
   *
   * <code>repeated string ss = 7;</code>
   * @return The count of ss.
   */
  public int getSsCount() {
    return ss_.size();
  }
  /**
   * <pre>
   * STRINGS
   * </pre>
   *
   * <code>repeated string ss = 7;</code>
   * @param index The index of the element to return.
   * @return The ss at the given index.
   */
  public java.lang.String getSs(int index) {
    return ss_.get(index);
  }
  /**
   * <pre>
   * STRINGS
   * </pre>
   *
   * <code>repeated string ss = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the ss at the given index.
   */
  public com.google.protobuf.ByteString
      getSsBytes(int index) {
    return ss_.getByteString(index);
  }

  public static final int BS_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.BooleanList bs_;
  /**
   * <pre>
   * BOOLS
   * </pre>
   *
   * <code>repeated bool bs = 8;</code>
   * @return A list containing the bs.
   */
  @java.lang.Override
  public java.util.List<java.lang.Boolean>
      getBsList() {
    return bs_;
  }
  /**
   * <pre>
   * BOOLS
   * </pre>
   *
   * <code>repeated bool bs = 8;</code>
   * @return The count of bs.
   */
  public int getBsCount() {
    return bs_.size();
  }
  /**
   * <pre>
   * BOOLS
   * </pre>
   *
   * <code>repeated bool bs = 8;</code>
   * @param index The index of the element to return.
   * @return The bs at the given index.
   */
  public boolean getBs(int index) {
    return bs_.getBoolean(index);
  }
  private int bsMemoizedSerializedSize = -1;

  public static final int IS_NA_FIELD_NUMBER = 9;
  private boolean isNa_ = false;
  /**
   * <pre>
   * Indicates the value is missing explicitly.
   * </pre>
   *
   * <code>bool is_na = 9;</code>
   * @return The isNa.
   */
  @java.lang.Override
  public boolean getIsNa() {
    return isNa_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (java.lang.Float.floatToRawIntBits(f_) != 0) {
      output.writeFloat(1, f_);
    }
    if (i64_ != 0L) {
      output.writeInt64(2, i64_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(s_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, s_);
    }
    if (b_ != false) {
      output.writeBool(4, b_);
    }
    if (getFsList().size() > 0) {
      output.writeUInt32NoTag(42);
      output.writeUInt32NoTag(fsMemoizedSerializedSize);
    }
    for (int i = 0; i < fs_.size(); i++) {
      output.writeFloatNoTag(fs_.getFloat(i));
    }
    if (getI64SList().size() > 0) {
      output.writeUInt32NoTag(50);
      output.writeUInt32NoTag(i64SMemoizedSerializedSize);
    }
    for (int i = 0; i < i64S_.size(); i++) {
      output.writeInt64NoTag(i64S_.getLong(i));
    }
    for (int i = 0; i < ss_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ss_.getRaw(i));
    }
    if (getBsList().size() > 0) {
      output.writeUInt32NoTag(66);
      output.writeUInt32NoTag(bsMemoizedSerializedSize);
    }
    for (int i = 0; i < bs_.size(); i++) {
      output.writeBoolNoTag(bs_.getBoolean(i));
    }
    if (isNa_ != false) {
      output.writeBool(9, isNa_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Float.floatToRawIntBits(f_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, f_);
    }
    if (i64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, i64_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(s_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, s_);
    }
    if (b_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, b_);
    }
    {
      int dataSize = 0;
      dataSize = 4 * getFsList().size();
      size += dataSize;
      if (!getFsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      fsMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < i64S_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(i64S_.getLong(i));
      }
      size += dataSize;
      if (!getI64SList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      i64SMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < ss_.size(); i++) {
        dataSize += computeStringSizeNoTag(ss_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSsList().size();
    }
    {
      int dataSize = 0;
      dataSize = 1 * getBsList().size();
      size += dataSize;
      if (!getBsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      bsMemoizedSerializedSize = dataSize;
    }
    if (isNa_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, isNa_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.secretflow.spec.v1.Attribute)) {
      return super.equals(obj);
    }
    com.secretflow.spec.v1.Attribute other = (com.secretflow.spec.v1.Attribute) obj;

    if (java.lang.Float.floatToIntBits(getF())
        != java.lang.Float.floatToIntBits(
            other.getF())) return false;
    if (getI64()
        != other.getI64()) return false;
    if (!getS()
        .equals(other.getS())) return false;
    if (getB()
        != other.getB()) return false;
    if (!getFsList()
        .equals(other.getFsList())) return false;
    if (!getI64SList()
        .equals(other.getI64SList())) return false;
    if (!getSsList()
        .equals(other.getSsList())) return false;
    if (!getBsList()
        .equals(other.getBsList())) return false;
    if (getIsNa()
        != other.getIsNa()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + F_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getF());
    hash = (37 * hash) + I64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getI64());
    hash = (37 * hash) + S_FIELD_NUMBER;
    hash = (53 * hash) + getS().hashCode();
    hash = (37 * hash) + B_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getB());
    if (getFsCount() > 0) {
      hash = (37 * hash) + FS_FIELD_NUMBER;
      hash = (53 * hash) + getFsList().hashCode();
    }
    if (getI64SCount() > 0) {
      hash = (37 * hash) + I64S_FIELD_NUMBER;
      hash = (53 * hash) + getI64SList().hashCode();
    }
    if (getSsCount() > 0) {
      hash = (37 * hash) + SS_FIELD_NUMBER;
      hash = (53 * hash) + getSsList().hashCode();
    }
    if (getBsCount() > 0) {
      hash = (37 * hash) + BS_FIELD_NUMBER;
      hash = (53 * hash) + getBsList().hashCode();
    }
    hash = (37 * hash) + IS_NA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsNa());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.secretflow.spec.v1.Attribute parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.Attribute parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Attribute parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.Attribute parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Attribute parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.Attribute parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Attribute parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.Attribute parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Attribute parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.Attribute parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Attribute parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.Attribute parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.secretflow.spec.v1.Attribute prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The value of an attribute
   * </pre>
   *
   * Protobuf type {@code secretflow.spec.v1.Attribute}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:secretflow.spec.v1.Attribute)
      com.secretflow.spec.v1.AttributeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_Attribute_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_Attribute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secretflow.spec.v1.Attribute.class, com.secretflow.spec.v1.Attribute.Builder.class);
    }

    // Construct using com.secretflow.spec.v1.Attribute.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      f_ = 0F;
      i64_ = 0L;
      s_ = "";
      b_ = false;
      fs_ = emptyFloatList();
      i64S_ = emptyLongList();
      ss_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      bs_ = emptyBooleanList();
      isNa_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_Attribute_descriptor;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.Attribute getDefaultInstanceForType() {
      return com.secretflow.spec.v1.Attribute.getDefaultInstance();
    }

    @java.lang.Override
    public com.secretflow.spec.v1.Attribute build() {
      com.secretflow.spec.v1.Attribute result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.Attribute buildPartial() {
      com.secretflow.spec.v1.Attribute result = new com.secretflow.spec.v1.Attribute(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.secretflow.spec.v1.Attribute result) {
      if (((bitField0_ & 0x00000010) != 0)) {
        fs_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.fs_ = fs_;
      if (((bitField0_ & 0x00000020) != 0)) {
        i64S_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000020);
      }
      result.i64S_ = i64S_;
      if (((bitField0_ & 0x00000080) != 0)) {
        bs_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000080);
      }
      result.bs_ = bs_;
    }

    private void buildPartial0(com.secretflow.spec.v1.Attribute result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.f_ = f_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.i64_ = i64_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.s_ = s_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.b_ = b_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        ss_.makeImmutable();
        result.ss_ = ss_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.isNa_ = isNa_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.secretflow.spec.v1.Attribute) {
        return mergeFrom((com.secretflow.spec.v1.Attribute)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.secretflow.spec.v1.Attribute other) {
      if (other == com.secretflow.spec.v1.Attribute.getDefaultInstance()) return this;
      if (other.getF() != 0F) {
        setF(other.getF());
      }
      if (other.getI64() != 0L) {
        setI64(other.getI64());
      }
      if (!other.getS().isEmpty()) {
        s_ = other.s_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getB() != false) {
        setB(other.getB());
      }
      if (!other.fs_.isEmpty()) {
        if (fs_.isEmpty()) {
          fs_ = other.fs_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureFsIsMutable();
          fs_.addAll(other.fs_);
        }
        onChanged();
      }
      if (!other.i64S_.isEmpty()) {
        if (i64S_.isEmpty()) {
          i64S_ = other.i64S_;
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          ensureI64SIsMutable();
          i64S_.addAll(other.i64S_);
        }
        onChanged();
      }
      if (!other.ss_.isEmpty()) {
        if (ss_.isEmpty()) {
          ss_ = other.ss_;
          bitField0_ |= 0x00000040;
        } else {
          ensureSsIsMutable();
          ss_.addAll(other.ss_);
        }
        onChanged();
      }
      if (!other.bs_.isEmpty()) {
        if (bs_.isEmpty()) {
          bs_ = other.bs_;
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          ensureBsIsMutable();
          bs_.addAll(other.bs_);
        }
        onChanged();
      }
      if (other.getIsNa() != false) {
        setIsNa(other.getIsNa());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              f_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 16: {
              i64_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              s_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              b_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 45: {
              float v = input.readFloat();
              ensureFsIsMutable();
              fs_.addFloat(v);
              break;
            } // case 45
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureFsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                fs_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 42
            case 48: {
              long v = input.readInt64();
              ensureI64SIsMutable();
              i64S_.addLong(v);
              break;
            } // case 48
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureI64SIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                i64S_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 50
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureSsIsMutable();
              ss_.add(s);
              break;
            } // case 58
            case 64: {
              boolean v = input.readBool();
              ensureBsIsMutable();
              bs_.addBoolean(v);
              break;
            } // case 64
            case 66: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureBsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                bs_.addBoolean(input.readBool());
              }
              input.popLimit(limit);
              break;
            } // case 66
            case 72: {
              isNa_ = input.readBool();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private float f_ ;
    /**
     * <pre>
     * FLOAT
     * </pre>
     *
     * <code>float f = 1;</code>
     * @return The f.
     */
    @java.lang.Override
    public float getF() {
      return f_;
    }
    /**
     * <pre>
     * FLOAT
     * </pre>
     *
     * <code>float f = 1;</code>
     * @param value The f to set.
     * @return This builder for chaining.
     */
    public Builder setF(float value) {

      f_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * FLOAT
     * </pre>
     *
     * <code>float f = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearF() {
      bitField0_ = (bitField0_ & ~0x00000001);
      f_ = 0F;
      onChanged();
      return this;
    }

    private long i64_ ;
    /**
     * <pre>
     * INT
     * NOTE(junfeng): "is" is preserved by Python. Replaced with "i64".
     * </pre>
     *
     * <code>int64 i64 = 2;</code>
     * @return The i64.
     */
    @java.lang.Override
    public long getI64() {
      return i64_;
    }
    /**
     * <pre>
     * INT
     * NOTE(junfeng): "is" is preserved by Python. Replaced with "i64".
     * </pre>
     *
     * <code>int64 i64 = 2;</code>
     * @param value The i64 to set.
     * @return This builder for chaining.
     */
    public Builder setI64(long value) {

      i64_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * INT
     * NOTE(junfeng): "is" is preserved by Python. Replaced with "i64".
     * </pre>
     *
     * <code>int64 i64 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearI64() {
      bitField0_ = (bitField0_ & ~0x00000002);
      i64_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object s_ = "";
    /**
     * <pre>
     * STRING
     * </pre>
     *
     * <code>string s = 3;</code>
     * @return The s.
     */
    public java.lang.String getS() {
      java.lang.Object ref = s_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        s_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * STRING
     * </pre>
     *
     * <code>string s = 3;</code>
     * @return The bytes for s.
     */
    public com.google.protobuf.ByteString
        getSBytes() {
      java.lang.Object ref = s_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * STRING
     * </pre>
     *
     * <code>string s = 3;</code>
     * @param value The s to set.
     * @return This builder for chaining.
     */
    public Builder setS(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      s_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * STRING
     * </pre>
     *
     * <code>string s = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearS() {
      s_ = getDefaultInstance().getS();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * STRING
     * </pre>
     *
     * <code>string s = 3;</code>
     * @param value The bytes for s to set.
     * @return This builder for chaining.
     */
    public Builder setSBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      s_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private boolean b_ ;
    /**
     * <pre>
     * BOOL
     * </pre>
     *
     * <code>bool b = 4;</code>
     * @return The b.
     */
    @java.lang.Override
    public boolean getB() {
      return b_;
    }
    /**
     * <pre>
     * BOOL
     * </pre>
     *
     * <code>bool b = 4;</code>
     * @param value The b to set.
     * @return This builder for chaining.
     */
    public Builder setB(boolean value) {

      b_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BOOL
     * </pre>
     *
     * <code>bool b = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearB() {
      bitField0_ = (bitField0_ & ~0x00000008);
      b_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.FloatList fs_ = emptyFloatList();
    private void ensureFsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        fs_ = mutableCopy(fs_);
        bitField0_ |= 0x00000010;
      }
    }
    /**
     * <pre>
     * FLOATS
     * </pre>
     *
     * <code>repeated float fs = 5;</code>
     * @return A list containing the fs.
     */
    public java.util.List<java.lang.Float>
        getFsList() {
      return ((bitField0_ & 0x00000010) != 0) ?
               java.util.Collections.unmodifiableList(fs_) : fs_;
    }
    /**
     * <pre>
     * FLOATS
     * </pre>
     *
     * <code>repeated float fs = 5;</code>
     * @return The count of fs.
     */
    public int getFsCount() {
      return fs_.size();
    }
    /**
     * <pre>
     * FLOATS
     * </pre>
     *
     * <code>repeated float fs = 5;</code>
     * @param index The index of the element to return.
     * @return The fs at the given index.
     */
    public float getFs(int index) {
      return fs_.getFloat(index);
    }
    /**
     * <pre>
     * FLOATS
     * </pre>
     *
     * <code>repeated float fs = 5;</code>
     * @param index The index to set the value at.
     * @param value The fs to set.
     * @return This builder for chaining.
     */
    public Builder setFs(
        int index, float value) {

      ensureFsIsMutable();
      fs_.setFloat(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * FLOATS
     * </pre>
     *
     * <code>repeated float fs = 5;</code>
     * @param value The fs to add.
     * @return This builder for chaining.
     */
    public Builder addFs(float value) {

      ensureFsIsMutable();
      fs_.addFloat(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * FLOATS
     * </pre>
     *
     * <code>repeated float fs = 5;</code>
     * @param values The fs to add.
     * @return This builder for chaining.
     */
    public Builder addAllFs(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureFsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, fs_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * FLOATS
     * </pre>
     *
     * <code>repeated float fs = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFs() {
      fs_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList i64S_ = emptyLongList();
    private void ensureI64SIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        i64S_ = mutableCopy(i64S_);
        bitField0_ |= 0x00000020;
      }
    }
    /**
     * <pre>
     * INTS
     * </pre>
     *
     * <code>repeated int64 i64s = 6;</code>
     * @return A list containing the i64s.
     */
    public java.util.List<java.lang.Long>
        getI64SList() {
      return ((bitField0_ & 0x00000020) != 0) ?
               java.util.Collections.unmodifiableList(i64S_) : i64S_;
    }
    /**
     * <pre>
     * INTS
     * </pre>
     *
     * <code>repeated int64 i64s = 6;</code>
     * @return The count of i64s.
     */
    public int getI64SCount() {
      return i64S_.size();
    }
    /**
     * <pre>
     * INTS
     * </pre>
     *
     * <code>repeated int64 i64s = 6;</code>
     * @param index The index of the element to return.
     * @return The i64s at the given index.
     */
    public long getI64S(int index) {
      return i64S_.getLong(index);
    }
    /**
     * <pre>
     * INTS
     * </pre>
     *
     * <code>repeated int64 i64s = 6;</code>
     * @param index The index to set the value at.
     * @param value The i64s to set.
     * @return This builder for chaining.
     */
    public Builder setI64S(
        int index, long value) {

      ensureI64SIsMutable();
      i64S_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * INTS
     * </pre>
     *
     * <code>repeated int64 i64s = 6;</code>
     * @param value The i64s to add.
     * @return This builder for chaining.
     */
    public Builder addI64S(long value) {

      ensureI64SIsMutable();
      i64S_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * INTS
     * </pre>
     *
     * <code>repeated int64 i64s = 6;</code>
     * @param values The i64s to add.
     * @return This builder for chaining.
     */
    public Builder addAllI64S(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureI64SIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, i64S_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * INTS
     * </pre>
     *
     * <code>repeated int64 i64s = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearI64S() {
      i64S_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList ss_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureSsIsMutable() {
      if (!ss_.isModifiable()) {
        ss_ = new com.google.protobuf.LazyStringArrayList(ss_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <pre>
     * STRINGS
     * </pre>
     *
     * <code>repeated string ss = 7;</code>
     * @return A list containing the ss.
     */
    public com.google.protobuf.ProtocolStringList
        getSsList() {
      ss_.makeImmutable();
      return ss_;
    }
    /**
     * <pre>
     * STRINGS
     * </pre>
     *
     * <code>repeated string ss = 7;</code>
     * @return The count of ss.
     */
    public int getSsCount() {
      return ss_.size();
    }
    /**
     * <pre>
     * STRINGS
     * </pre>
     *
     * <code>repeated string ss = 7;</code>
     * @param index The index of the element to return.
     * @return The ss at the given index.
     */
    public java.lang.String getSs(int index) {
      return ss_.get(index);
    }
    /**
     * <pre>
     * STRINGS
     * </pre>
     *
     * <code>repeated string ss = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the ss at the given index.
     */
    public com.google.protobuf.ByteString
        getSsBytes(int index) {
      return ss_.getByteString(index);
    }
    /**
     * <pre>
     * STRINGS
     * </pre>
     *
     * <code>repeated string ss = 7;</code>
     * @param index The index to set the value at.
     * @param value The ss to set.
     * @return This builder for chaining.
     */
    public Builder setSs(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSsIsMutable();
      ss_.set(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * STRINGS
     * </pre>
     *
     * <code>repeated string ss = 7;</code>
     * @param value The ss to add.
     * @return This builder for chaining.
     */
    public Builder addSs(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSsIsMutable();
      ss_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * STRINGS
     * </pre>
     *
     * <code>repeated string ss = 7;</code>
     * @param values The ss to add.
     * @return This builder for chaining.
     */
    public Builder addAllSs(
        java.lang.Iterable<java.lang.String> values) {
      ensureSsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, ss_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * STRINGS
     * </pre>
     *
     * <code>repeated string ss = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSs() {
      ss_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * STRINGS
     * </pre>
     *
     * <code>repeated string ss = 7;</code>
     * @param value The bytes of the ss to add.
     * @return This builder for chaining.
     */
    public Builder addSsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureSsIsMutable();
      ss_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.BooleanList bs_ = emptyBooleanList();
    private void ensureBsIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        bs_ = mutableCopy(bs_);
        bitField0_ |= 0x00000080;
      }
    }
    /**
     * <pre>
     * BOOLS
     * </pre>
     *
     * <code>repeated bool bs = 8;</code>
     * @return A list containing the bs.
     */
    public java.util.List<java.lang.Boolean>
        getBsList() {
      return ((bitField0_ & 0x00000080) != 0) ?
               java.util.Collections.unmodifiableList(bs_) : bs_;
    }
    /**
     * <pre>
     * BOOLS
     * </pre>
     *
     * <code>repeated bool bs = 8;</code>
     * @return The count of bs.
     */
    public int getBsCount() {
      return bs_.size();
    }
    /**
     * <pre>
     * BOOLS
     * </pre>
     *
     * <code>repeated bool bs = 8;</code>
     * @param index The index of the element to return.
     * @return The bs at the given index.
     */
    public boolean getBs(int index) {
      return bs_.getBoolean(index);
    }
    /**
     * <pre>
     * BOOLS
     * </pre>
     *
     * <code>repeated bool bs = 8;</code>
     * @param index The index to set the value at.
     * @param value The bs to set.
     * @return This builder for chaining.
     */
    public Builder setBs(
        int index, boolean value) {

      ensureBsIsMutable();
      bs_.setBoolean(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BOOLS
     * </pre>
     *
     * <code>repeated bool bs = 8;</code>
     * @param value The bs to add.
     * @return This builder for chaining.
     */
    public Builder addBs(boolean value) {

      ensureBsIsMutable();
      bs_.addBoolean(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BOOLS
     * </pre>
     *
     * <code>repeated bool bs = 8;</code>
     * @param values The bs to add.
     * @return This builder for chaining.
     */
    public Builder addAllBs(
        java.lang.Iterable<? extends java.lang.Boolean> values) {
      ensureBsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, bs_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BOOLS
     * </pre>
     *
     * <code>repeated bool bs = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearBs() {
      bs_ = emptyBooleanList();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }

    private boolean isNa_ ;
    /**
     * <pre>
     * Indicates the value is missing explicitly.
     * </pre>
     *
     * <code>bool is_na = 9;</code>
     * @return The isNa.
     */
    @java.lang.Override
    public boolean getIsNa() {
      return isNa_;
    }
    /**
     * <pre>
     * Indicates the value is missing explicitly.
     * </pre>
     *
     * <code>bool is_na = 9;</code>
     * @param value The isNa to set.
     * @return This builder for chaining.
     */
    public Builder setIsNa(boolean value) {

      isNa_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates the value is missing explicitly.
     * </pre>
     *
     * <code>bool is_na = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsNa() {
      bitField0_ = (bitField0_ & ~0x00000100);
      isNa_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:secretflow.spec.v1.Attribute)
  }

  // @@protoc_insertion_point(class_scope:secretflow.spec.v1.Attribute)
  private static final com.secretflow.spec.v1.Attribute DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.secretflow.spec.v1.Attribute();
  }

  public static com.secretflow.spec.v1.Attribute getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Attribute>
      PARSER = new com.google.protobuf.AbstractParser<Attribute>() {
    @java.lang.Override
    public Attribute parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Attribute> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Attribute> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.secretflow.spec.v1.Attribute getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

