// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/spec/v1/component.proto

package com.secretflow.spec.v1;

/**
 * <pre>
 * Supported attribute types.
 * </pre>
 *
 * Protobuf enum {@code secretflow.spec.v1.AttrType}
 */
public enum AttrType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ATTR_TYPE_UNSPECIFIED = 0;</code>
   */
  ATTR_TYPE_UNSPECIFIED(0),
  /**
   * <pre>
   * FLOAT
   * </pre>
   *
   * <code>AT_FLOAT = 1;</code>
   */
  AT_FLOAT(1),
  /**
   * <pre>
   * INT
   * </pre>
   *
   * <code>AT_INT = 2;</code>
   */
  AT_INT(2),
  /**
   * <pre>
   * STRING
   * </pre>
   *
   * <code>AT_STRING = 3;</code>
   */
  AT_STRING(3),
  /**
   * <pre>
   * BOOL
   * </pre>
   *
   * <code>AT_BOOL = 4;</code>
   */
  AT_BOOL(4),
  /**
   * <pre>
   * FLOATS
   * </pre>
   *
   * <code>AT_FLOATS = 5;</code>
   */
  AT_FLOATS(5),
  /**
   * <pre>
   * INTS
   * </pre>
   *
   * <code>AT_INTS = 6;</code>
   */
  AT_INTS(6),
  /**
   * <pre>
   * STRINGS
   * </pre>
   *
   * <code>AT_STRINGS = 7;</code>
   */
  AT_STRINGS(7),
  /**
   * <pre>
   * BOOLS
   * </pre>
   *
   * <code>AT_BOOLS = 8;</code>
   */
  AT_BOOLS(8),
  /**
   * <code>AT_STRUCT_GROUP = 9;</code>
   */
  AT_STRUCT_GROUP(9),
  /**
   * <code>AT_UNION_GROUP = 10;</code>
   */
  AT_UNION_GROUP(10),
  /**
   * <code>AT_SF_TABLE_COL = 11;</code>
   */
  AT_SF_TABLE_COL(11),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ATTR_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int ATTR_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * FLOAT
   * </pre>
   *
   * <code>AT_FLOAT = 1;</code>
   */
  public static final int AT_FLOAT_VALUE = 1;
  /**
   * <pre>
   * INT
   * </pre>
   *
   * <code>AT_INT = 2;</code>
   */
  public static final int AT_INT_VALUE = 2;
  /**
   * <pre>
   * STRING
   * </pre>
   *
   * <code>AT_STRING = 3;</code>
   */
  public static final int AT_STRING_VALUE = 3;
  /**
   * <pre>
   * BOOL
   * </pre>
   *
   * <code>AT_BOOL = 4;</code>
   */
  public static final int AT_BOOL_VALUE = 4;
  /**
   * <pre>
   * FLOATS
   * </pre>
   *
   * <code>AT_FLOATS = 5;</code>
   */
  public static final int AT_FLOATS_VALUE = 5;
  /**
   * <pre>
   * INTS
   * </pre>
   *
   * <code>AT_INTS = 6;</code>
   */
  public static final int AT_INTS_VALUE = 6;
  /**
   * <pre>
   * STRINGS
   * </pre>
   *
   * <code>AT_STRINGS = 7;</code>
   */
  public static final int AT_STRINGS_VALUE = 7;
  /**
   * <pre>
   * BOOLS
   * </pre>
   *
   * <code>AT_BOOLS = 8;</code>
   */
  public static final int AT_BOOLS_VALUE = 8;
  /**
   * <code>AT_STRUCT_GROUP = 9;</code>
   */
  public static final int AT_STRUCT_GROUP_VALUE = 9;
  /**
   * <code>AT_UNION_GROUP = 10;</code>
   */
  public static final int AT_UNION_GROUP_VALUE = 10;
  /**
   * <code>AT_SF_TABLE_COL = 11;</code>
   */
  public static final int AT_SF_TABLE_COL_VALUE = 11;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AttrType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AttrType forNumber(int value) {
    switch (value) {
      case 0: return ATTR_TYPE_UNSPECIFIED;
      case 1: return AT_FLOAT;
      case 2: return AT_INT;
      case 3: return AT_STRING;
      case 4: return AT_BOOL;
      case 5: return AT_FLOATS;
      case 6: return AT_INTS;
      case 7: return AT_STRINGS;
      case 8: return AT_BOOLS;
      case 9: return AT_STRUCT_GROUP;
      case 10: return AT_UNION_GROUP;
      case 11: return AT_SF_TABLE_COL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AttrType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AttrType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AttrType>() {
          public AttrType findValueByNumber(int number) {
            return AttrType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.secretflow.spec.v1.ComponentProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final AttrType[] VALUES = values();

  public static AttrType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AttrType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:secretflow.spec.v1.AttrType)
}

