// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/spec/v1/component.proto

package com.secretflow.spec.v1;

public final class ComponentProto {
  private ComponentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_spec_v1_Attribute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_spec_v1_Attribute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_spec_v1_AttributeDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_spec_v1_AttributeDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_spec_v1_AttributeDef_AtomicAttrDesc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_spec_v1_AttributeDef_AtomicAttrDesc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_spec_v1_AttributeDef_UnionAttrGroupDesc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_spec_v1_AttributeDef_UnionAttrGroupDesc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_spec_v1_IoDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_spec_v1_IoDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_spec_v1_IoDef_TableAttrDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_spec_v1_IoDef_TableAttrDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_spec_v1_ComponentDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_spec_v1_ComponentDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secretflow_spec_v1_CompListDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_secretflow_spec_v1_CompListDef_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"secretflow/spec/v1/component.proto\022\022se" +
      "cretflow.spec.v1\"z\n\tAttribute\022\t\n\001f\030\001 \001(\002" +
      "\022\013\n\003i64\030\002 \001(\003\022\t\n\001s\030\003 \001(\t\022\t\n\001b\030\004 \001(\010\022\n\n\002f" +
      "s\030\005 \003(\002\022\014\n\004i64s\030\006 \003(\003\022\n\n\002ss\030\007 \003(\t\022\n\n\002bs\030" +
      "\010 \003(\010\022\r\n\005is_na\030\t \001(\010\"\331\005\n\014AttributeDef\022\020\n" +
      "\010prefixes\030\001 \003(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004desc\030\003 " +
      "\001(\t\022*\n\004type\030\004 \001(\0162\034.secretflow.spec.v1.A" +
      "ttrType\022?\n\006atomic\030\005 \001(\0132/.secretflow.spe" +
      "c.v1.AttributeDef.AtomicAttrDesc\022B\n\005unio" +
      "n\030\006 \001(\01323.secretflow.spec.v1.AttributeDe" +
      "f.UnionAttrGroupDesc\032\270\003\n\016AtomicAttrDesc\022" +
      "!\n\031list_min_length_inclusive\030\001 \001(\003\022!\n\031li" +
      "st_max_length_inclusive\030\002 \001(\003\022\023\n\013is_opti" +
      "onal\030\003 \001(\010\0224\n\rdefault_value\030\004 \001(\0132\035.secr" +
      "etflow.spec.v1.Attribute\0225\n\016allowed_valu" +
      "es\030\005 \001(\0132\035.secretflow.spec.v1.Attribute\022" +
      "\033\n\023lower_bound_enabled\030\006 \001(\010\0222\n\013lower_bo" +
      "und\030\007 \001(\0132\035.secretflow.spec.v1.Attribute" +
      "\022\035\n\025lower_bound_inclusive\030\010 \001(\010\022\033\n\023upper" +
      "_bound_enabled\030\t \001(\010\0222\n\013upper_bound\030\n \001(" +
      "\0132\035.secretflow.spec.v1.Attribute\022\035\n\025uppe" +
      "r_bound_inclusive\030\013 \001(\010\032/\n\022UnionAttrGrou" +
      "pDesc\022\031\n\021default_selection\030\001 \001(\t\"\232\002\n\005IoD" +
      "ef\022\014\n\004name\030\001 \001(\t\022\014\n\004desc\030\002 \001(\t\022\r\n\005types\030" +
      "\003 \003(\t\0225\n\005attrs\030\004 \003(\0132&.secretflow.spec.v" +
      "1.IoDef.TableAttrDef\032\256\001\n\014TableAttrDef\022\014\n" +
      "\004name\030\001 \001(\t\022\014\n\004desc\030\002 \001(\t\022\r\n\005types\030\003 \003(\t" +
      "\022\035\n\025col_min_cnt_inclusive\030\004 \001(\003\022\035\n\025col_m" +
      "ax_cnt_inclusive\030\005 \001(\003\0225\n\013extra_attrs\030\006 " +
      "\003(\0132 .secretflow.spec.v1.AttributeDef\"\323\001" +
      "\n\014ComponentDef\022\016\n\006domain\030\001 \001(\t\022\014\n\004name\030\002" +
      " \001(\t\022\014\n\004desc\030\003 \001(\t\022\017\n\007version\030\004 \001(\t\022/\n\005a" +
      "ttrs\030\005 \003(\0132 .secretflow.spec.v1.Attribut" +
      "eDef\022)\n\006inputs\030\006 \003(\0132\031.secretflow.spec.v" +
      "1.IoDef\022*\n\007outputs\030\007 \003(\0132\031.secretflow.sp" +
      "ec.v1.IoDef\"k\n\013CompListDef\022\014\n\004name\030\001 \001(\t" +
      "\022\014\n\004desc\030\002 \001(\t\022\017\n\007version\030\003 \001(\t\022/\n\005comps" +
      "\030\004 \003(\0132 .secretflow.spec.v1.ComponentDef" +
      "*\323\001\n\010AttrType\022\031\n\025ATTR_TYPE_UNSPECIFIED\020\000" +
      "\022\014\n\010AT_FLOAT\020\001\022\n\n\006AT_INT\020\002\022\r\n\tAT_STRING\020" +
      "\003\022\013\n\007AT_BOOL\020\004\022\r\n\tAT_FLOATS\020\005\022\013\n\007AT_INTS" +
      "\020\006\022\016\n\nAT_STRINGS\020\007\022\014\n\010AT_BOOLS\020\010\022\023\n\017AT_S" +
      "TRUCT_GROUP\020\t\022\022\n\016AT_UNION_GROUP\020\n\022\023\n\017AT_" +
      "SF_TABLE_COL\020\013B*\n\026com.secretflow.spec.v1" +
      "B\016ComponentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_secretflow_spec_v1_Attribute_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_secretflow_spec_v1_Attribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_spec_v1_Attribute_descriptor,
        new java.lang.String[] { "F", "I64", "S", "B", "Fs", "I64S", "Ss", "Bs", "IsNa", });
    internal_static_secretflow_spec_v1_AttributeDef_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_secretflow_spec_v1_AttributeDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_spec_v1_AttributeDef_descriptor,
        new java.lang.String[] { "Prefixes", "Name", "Desc", "Type", "Atomic", "Union", });
    internal_static_secretflow_spec_v1_AttributeDef_AtomicAttrDesc_descriptor =
      internal_static_secretflow_spec_v1_AttributeDef_descriptor.getNestedTypes().get(0);
    internal_static_secretflow_spec_v1_AttributeDef_AtomicAttrDesc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_spec_v1_AttributeDef_AtomicAttrDesc_descriptor,
        new java.lang.String[] { "ListMinLengthInclusive", "ListMaxLengthInclusive", "IsOptional", "DefaultValue", "AllowedValues", "LowerBoundEnabled", "LowerBound", "LowerBoundInclusive", "UpperBoundEnabled", "UpperBound", "UpperBoundInclusive", });
    internal_static_secretflow_spec_v1_AttributeDef_UnionAttrGroupDesc_descriptor =
      internal_static_secretflow_spec_v1_AttributeDef_descriptor.getNestedTypes().get(1);
    internal_static_secretflow_spec_v1_AttributeDef_UnionAttrGroupDesc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_spec_v1_AttributeDef_UnionAttrGroupDesc_descriptor,
        new java.lang.String[] { "DefaultSelection", });
    internal_static_secretflow_spec_v1_IoDef_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_secretflow_spec_v1_IoDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_spec_v1_IoDef_descriptor,
        new java.lang.String[] { "Name", "Desc", "Types", "Attrs", });
    internal_static_secretflow_spec_v1_IoDef_TableAttrDef_descriptor =
      internal_static_secretflow_spec_v1_IoDef_descriptor.getNestedTypes().get(0);
    internal_static_secretflow_spec_v1_IoDef_TableAttrDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_spec_v1_IoDef_TableAttrDef_descriptor,
        new java.lang.String[] { "Name", "Desc", "Types", "ColMinCntInclusive", "ColMaxCntInclusive", "ExtraAttrs", });
    internal_static_secretflow_spec_v1_ComponentDef_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_secretflow_spec_v1_ComponentDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_spec_v1_ComponentDef_descriptor,
        new java.lang.String[] { "Domain", "Name", "Desc", "Version", "Attrs", "Inputs", "Outputs", });
    internal_static_secretflow_spec_v1_CompListDef_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_secretflow_spec_v1_CompListDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_secretflow_spec_v1_CompListDef_descriptor,
        new java.lang.String[] { "Name", "Desc", "Version", "Comps", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
