// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/spec/v1/report.proto

package com.secretflow.spec.v1;

/**
 * <pre>
 * A division or a section of a page.
 * </pre>
 *
 * Protobuf type {@code secretflow.spec.v1.Div}
 */
public final class Div extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:secretflow.spec.v1.Div)
    DivOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Div.newBuilder() to construct.
  private Div(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Div() {
    name_ = "";
    desc_ = "";
    children_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Div();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Div_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Div_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.secretflow.spec.v1.Div.class, com.secretflow.spec.v1.Div.Builder.class);
  }

  public interface ChildOrBuilder extends
      // @@protoc_insertion_point(interface_extends:secretflow.spec.v1.Div.Child)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Supported: descriptions, table, div.
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <pre>
     * Supported: descriptions, table, div.
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
     * @return Whether the descriptions field is set.
     */
    boolean hasDescriptions();
    /**
     * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
     * @return The descriptions.
     */
    com.secretflow.spec.v1.Descriptions getDescriptions();
    /**
     * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
     */
    com.secretflow.spec.v1.DescriptionsOrBuilder getDescriptionsOrBuilder();

    /**
     * <code>.secretflow.spec.v1.Table table = 3;</code>
     * @return Whether the table field is set.
     */
    boolean hasTable();
    /**
     * <code>.secretflow.spec.v1.Table table = 3;</code>
     * @return The table.
     */
    com.secretflow.spec.v1.Table getTable();
    /**
     * <code>.secretflow.spec.v1.Table table = 3;</code>
     */
    com.secretflow.spec.v1.TableOrBuilder getTableOrBuilder();

    /**
     * <code>.secretflow.spec.v1.Div div = 4;</code>
     * @return Whether the div field is set.
     */
    boolean hasDiv();
    /**
     * <code>.secretflow.spec.v1.Div div = 4;</code>
     * @return The div.
     */
    com.secretflow.spec.v1.Div getDiv();
    /**
     * <code>.secretflow.spec.v1.Div div = 4;</code>
     */
    com.secretflow.spec.v1.DivOrBuilder getDivOrBuilder();
  }
  /**
   * Protobuf type {@code secretflow.spec.v1.Div.Child}
   */
  public static final class Child extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:secretflow.spec.v1.Div.Child)
      ChildOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Child.newBuilder() to construct.
    private Child(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Child() {
      type_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Child();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Div_Child_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Div_Child_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secretflow.spec.v1.Div.Child.class, com.secretflow.spec.v1.Div.Child.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <pre>
     * Supported: descriptions, table, div.
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Supported: descriptions, table, div.
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTIONS_FIELD_NUMBER = 2;
    private com.secretflow.spec.v1.Descriptions descriptions_;
    /**
     * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
     * @return Whether the descriptions field is set.
     */
    @java.lang.Override
    public boolean hasDescriptions() {
      return descriptions_ != null;
    }
    /**
     * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
     * @return The descriptions.
     */
    @java.lang.Override
    public com.secretflow.spec.v1.Descriptions getDescriptions() {
      return descriptions_ == null ? com.secretflow.spec.v1.Descriptions.getDefaultInstance() : descriptions_;
    }
    /**
     * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
     */
    @java.lang.Override
    public com.secretflow.spec.v1.DescriptionsOrBuilder getDescriptionsOrBuilder() {
      return descriptions_ == null ? com.secretflow.spec.v1.Descriptions.getDefaultInstance() : descriptions_;
    }

    public static final int TABLE_FIELD_NUMBER = 3;
    private com.secretflow.spec.v1.Table table_;
    /**
     * <code>.secretflow.spec.v1.Table table = 3;</code>
     * @return Whether the table field is set.
     */
    @java.lang.Override
    public boolean hasTable() {
      return table_ != null;
    }
    /**
     * <code>.secretflow.spec.v1.Table table = 3;</code>
     * @return The table.
     */
    @java.lang.Override
    public com.secretflow.spec.v1.Table getTable() {
      return table_ == null ? com.secretflow.spec.v1.Table.getDefaultInstance() : table_;
    }
    /**
     * <code>.secretflow.spec.v1.Table table = 3;</code>
     */
    @java.lang.Override
    public com.secretflow.spec.v1.TableOrBuilder getTableOrBuilder() {
      return table_ == null ? com.secretflow.spec.v1.Table.getDefaultInstance() : table_;
    }

    public static final int DIV_FIELD_NUMBER = 4;
    private com.secretflow.spec.v1.Div div_;
    /**
     * <code>.secretflow.spec.v1.Div div = 4;</code>
     * @return Whether the div field is set.
     */
    @java.lang.Override
    public boolean hasDiv() {
      return div_ != null;
    }
    /**
     * <code>.secretflow.spec.v1.Div div = 4;</code>
     * @return The div.
     */
    @java.lang.Override
    public com.secretflow.spec.v1.Div getDiv() {
      return div_ == null ? com.secretflow.spec.v1.Div.getDefaultInstance() : div_;
    }
    /**
     * <code>.secretflow.spec.v1.Div div = 4;</code>
     */
    @java.lang.Override
    public com.secretflow.spec.v1.DivOrBuilder getDivOrBuilder() {
      return div_ == null ? com.secretflow.spec.v1.Div.getDefaultInstance() : div_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (descriptions_ != null) {
        output.writeMessage(2, getDescriptions());
      }
      if (table_ != null) {
        output.writeMessage(3, getTable());
      }
      if (div_ != null) {
        output.writeMessage(4, getDiv());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (descriptions_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDescriptions());
      }
      if (table_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTable());
      }
      if (div_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getDiv());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.secretflow.spec.v1.Div.Child)) {
        return super.equals(obj);
      }
      com.secretflow.spec.v1.Div.Child other = (com.secretflow.spec.v1.Div.Child) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (hasDescriptions() != other.hasDescriptions()) return false;
      if (hasDescriptions()) {
        if (!getDescriptions()
            .equals(other.getDescriptions())) return false;
      }
      if (hasTable() != other.hasTable()) return false;
      if (hasTable()) {
        if (!getTable()
            .equals(other.getTable())) return false;
      }
      if (hasDiv() != other.hasDiv()) return false;
      if (hasDiv()) {
        if (!getDiv()
            .equals(other.getDiv())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      if (hasDescriptions()) {
        hash = (37 * hash) + DESCRIPTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getDescriptions().hashCode();
      }
      if (hasTable()) {
        hash = (37 * hash) + TABLE_FIELD_NUMBER;
        hash = (53 * hash) + getTable().hashCode();
      }
      if (hasDiv()) {
        hash = (37 * hash) + DIV_FIELD_NUMBER;
        hash = (53 * hash) + getDiv().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.secretflow.spec.v1.Div.Child parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secretflow.spec.v1.Div.Child parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secretflow.spec.v1.Div.Child parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secretflow.spec.v1.Div.Child parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secretflow.spec.v1.Div.Child parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secretflow.spec.v1.Div.Child parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secretflow.spec.v1.Div.Child parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.secretflow.spec.v1.Div.Child parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.secretflow.spec.v1.Div.Child parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.secretflow.spec.v1.Div.Child parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.secretflow.spec.v1.Div.Child parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.secretflow.spec.v1.Div.Child parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.secretflow.spec.v1.Div.Child prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code secretflow.spec.v1.Div.Child}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:secretflow.spec.v1.Div.Child)
        com.secretflow.spec.v1.Div.ChildOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Div_Child_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Div_Child_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.secretflow.spec.v1.Div.Child.class, com.secretflow.spec.v1.Div.Child.Builder.class);
      }

      // Construct using com.secretflow.spec.v1.Div.Child.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = "";
        descriptions_ = null;
        if (descriptionsBuilder_ != null) {
          descriptionsBuilder_.dispose();
          descriptionsBuilder_ = null;
        }
        table_ = null;
        if (tableBuilder_ != null) {
          tableBuilder_.dispose();
          tableBuilder_ = null;
        }
        div_ = null;
        if (divBuilder_ != null) {
          divBuilder_.dispose();
          divBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Div_Child_descriptor;
      }

      @java.lang.Override
      public com.secretflow.spec.v1.Div.Child getDefaultInstanceForType() {
        return com.secretflow.spec.v1.Div.Child.getDefaultInstance();
      }

      @java.lang.Override
      public com.secretflow.spec.v1.Div.Child build() {
        com.secretflow.spec.v1.Div.Child result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.secretflow.spec.v1.Div.Child buildPartial() {
        com.secretflow.spec.v1.Div.Child result = new com.secretflow.spec.v1.Div.Child(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.secretflow.spec.v1.Div.Child result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.descriptions_ = descriptionsBuilder_ == null
              ? descriptions_
              : descriptionsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.table_ = tableBuilder_ == null
              ? table_
              : tableBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.div_ = divBuilder_ == null
              ? div_
              : divBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.secretflow.spec.v1.Div.Child) {
          return mergeFrom((com.secretflow.spec.v1.Div.Child)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.secretflow.spec.v1.Div.Child other) {
        if (other == com.secretflow.spec.v1.Div.Child.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasDescriptions()) {
          mergeDescriptions(other.getDescriptions());
        }
        if (other.hasTable()) {
          mergeTable(other.getTable());
        }
        if (other.hasDiv()) {
          mergeDiv(other.getDiv());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getDescriptionsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getTableFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getDivFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <pre>
       * Supported: descriptions, table, div.
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Supported: descriptions, table, div.
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Supported: descriptions, table, div.
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Supported: descriptions, table, div.
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Supported: descriptions, table, div.
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.secretflow.spec.v1.Descriptions descriptions_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.secretflow.spec.v1.Descriptions, com.secretflow.spec.v1.Descriptions.Builder, com.secretflow.spec.v1.DescriptionsOrBuilder> descriptionsBuilder_;
      /**
       * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
       * @return Whether the descriptions field is set.
       */
      public boolean hasDescriptions() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
       * @return The descriptions.
       */
      public com.secretflow.spec.v1.Descriptions getDescriptions() {
        if (descriptionsBuilder_ == null) {
          return descriptions_ == null ? com.secretflow.spec.v1.Descriptions.getDefaultInstance() : descriptions_;
        } else {
          return descriptionsBuilder_.getMessage();
        }
      }
      /**
       * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
       */
      public Builder setDescriptions(com.secretflow.spec.v1.Descriptions value) {
        if (descriptionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          descriptions_ = value;
        } else {
          descriptionsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
       */
      public Builder setDescriptions(
          com.secretflow.spec.v1.Descriptions.Builder builderForValue) {
        if (descriptionsBuilder_ == null) {
          descriptions_ = builderForValue.build();
        } else {
          descriptionsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
       */
      public Builder mergeDescriptions(com.secretflow.spec.v1.Descriptions value) {
        if (descriptionsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            descriptions_ != null &&
            descriptions_ != com.secretflow.spec.v1.Descriptions.getDefaultInstance()) {
            getDescriptionsBuilder().mergeFrom(value);
          } else {
            descriptions_ = value;
          }
        } else {
          descriptionsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
       */
      public Builder clearDescriptions() {
        bitField0_ = (bitField0_ & ~0x00000002);
        descriptions_ = null;
        if (descriptionsBuilder_ != null) {
          descriptionsBuilder_.dispose();
          descriptionsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
       */
      public com.secretflow.spec.v1.Descriptions.Builder getDescriptionsBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDescriptionsFieldBuilder().getBuilder();
      }
      /**
       * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
       */
      public com.secretflow.spec.v1.DescriptionsOrBuilder getDescriptionsOrBuilder() {
        if (descriptionsBuilder_ != null) {
          return descriptionsBuilder_.getMessageOrBuilder();
        } else {
          return descriptions_ == null ?
              com.secretflow.spec.v1.Descriptions.getDefaultInstance() : descriptions_;
        }
      }
      /**
       * <code>.secretflow.spec.v1.Descriptions descriptions = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.secretflow.spec.v1.Descriptions, com.secretflow.spec.v1.Descriptions.Builder, com.secretflow.spec.v1.DescriptionsOrBuilder> 
          getDescriptionsFieldBuilder() {
        if (descriptionsBuilder_ == null) {
          descriptionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.secretflow.spec.v1.Descriptions, com.secretflow.spec.v1.Descriptions.Builder, com.secretflow.spec.v1.DescriptionsOrBuilder>(
                  getDescriptions(),
                  getParentForChildren(),
                  isClean());
          descriptions_ = null;
        }
        return descriptionsBuilder_;
      }

      private com.secretflow.spec.v1.Table table_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.secretflow.spec.v1.Table, com.secretflow.spec.v1.Table.Builder, com.secretflow.spec.v1.TableOrBuilder> tableBuilder_;
      /**
       * <code>.secretflow.spec.v1.Table table = 3;</code>
       * @return Whether the table field is set.
       */
      public boolean hasTable() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.secretflow.spec.v1.Table table = 3;</code>
       * @return The table.
       */
      public com.secretflow.spec.v1.Table getTable() {
        if (tableBuilder_ == null) {
          return table_ == null ? com.secretflow.spec.v1.Table.getDefaultInstance() : table_;
        } else {
          return tableBuilder_.getMessage();
        }
      }
      /**
       * <code>.secretflow.spec.v1.Table table = 3;</code>
       */
      public Builder setTable(com.secretflow.spec.v1.Table value) {
        if (tableBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          table_ = value;
        } else {
          tableBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.spec.v1.Table table = 3;</code>
       */
      public Builder setTable(
          com.secretflow.spec.v1.Table.Builder builderForValue) {
        if (tableBuilder_ == null) {
          table_ = builderForValue.build();
        } else {
          tableBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.spec.v1.Table table = 3;</code>
       */
      public Builder mergeTable(com.secretflow.spec.v1.Table value) {
        if (tableBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            table_ != null &&
            table_ != com.secretflow.spec.v1.Table.getDefaultInstance()) {
            getTableBuilder().mergeFrom(value);
          } else {
            table_ = value;
          }
        } else {
          tableBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.spec.v1.Table table = 3;</code>
       */
      public Builder clearTable() {
        bitField0_ = (bitField0_ & ~0x00000004);
        table_ = null;
        if (tableBuilder_ != null) {
          tableBuilder_.dispose();
          tableBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.spec.v1.Table table = 3;</code>
       */
      public com.secretflow.spec.v1.Table.Builder getTableBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTableFieldBuilder().getBuilder();
      }
      /**
       * <code>.secretflow.spec.v1.Table table = 3;</code>
       */
      public com.secretflow.spec.v1.TableOrBuilder getTableOrBuilder() {
        if (tableBuilder_ != null) {
          return tableBuilder_.getMessageOrBuilder();
        } else {
          return table_ == null ?
              com.secretflow.spec.v1.Table.getDefaultInstance() : table_;
        }
      }
      /**
       * <code>.secretflow.spec.v1.Table table = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.secretflow.spec.v1.Table, com.secretflow.spec.v1.Table.Builder, com.secretflow.spec.v1.TableOrBuilder> 
          getTableFieldBuilder() {
        if (tableBuilder_ == null) {
          tableBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.secretflow.spec.v1.Table, com.secretflow.spec.v1.Table.Builder, com.secretflow.spec.v1.TableOrBuilder>(
                  getTable(),
                  getParentForChildren(),
                  isClean());
          table_ = null;
        }
        return tableBuilder_;
      }

      private com.secretflow.spec.v1.Div div_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.secretflow.spec.v1.Div, com.secretflow.spec.v1.Div.Builder, com.secretflow.spec.v1.DivOrBuilder> divBuilder_;
      /**
       * <code>.secretflow.spec.v1.Div div = 4;</code>
       * @return Whether the div field is set.
       */
      public boolean hasDiv() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.secretflow.spec.v1.Div div = 4;</code>
       * @return The div.
       */
      public com.secretflow.spec.v1.Div getDiv() {
        if (divBuilder_ == null) {
          return div_ == null ? com.secretflow.spec.v1.Div.getDefaultInstance() : div_;
        } else {
          return divBuilder_.getMessage();
        }
      }
      /**
       * <code>.secretflow.spec.v1.Div div = 4;</code>
       */
      public Builder setDiv(com.secretflow.spec.v1.Div value) {
        if (divBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          div_ = value;
        } else {
          divBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.spec.v1.Div div = 4;</code>
       */
      public Builder setDiv(
          com.secretflow.spec.v1.Div.Builder builderForValue) {
        if (divBuilder_ == null) {
          div_ = builderForValue.build();
        } else {
          divBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.spec.v1.Div div = 4;</code>
       */
      public Builder mergeDiv(com.secretflow.spec.v1.Div value) {
        if (divBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            div_ != null &&
            div_ != com.secretflow.spec.v1.Div.getDefaultInstance()) {
            getDivBuilder().mergeFrom(value);
          } else {
            div_ = value;
          }
        } else {
          divBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.spec.v1.Div div = 4;</code>
       */
      public Builder clearDiv() {
        bitField0_ = (bitField0_ & ~0x00000008);
        div_ = null;
        if (divBuilder_ != null) {
          divBuilder_.dispose();
          divBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.secretflow.spec.v1.Div div = 4;</code>
       */
      public com.secretflow.spec.v1.Div.Builder getDivBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getDivFieldBuilder().getBuilder();
      }
      /**
       * <code>.secretflow.spec.v1.Div div = 4;</code>
       */
      public com.secretflow.spec.v1.DivOrBuilder getDivOrBuilder() {
        if (divBuilder_ != null) {
          return divBuilder_.getMessageOrBuilder();
        } else {
          return div_ == null ?
              com.secretflow.spec.v1.Div.getDefaultInstance() : div_;
        }
      }
      /**
       * <code>.secretflow.spec.v1.Div div = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.secretflow.spec.v1.Div, com.secretflow.spec.v1.Div.Builder, com.secretflow.spec.v1.DivOrBuilder> 
          getDivFieldBuilder() {
        if (divBuilder_ == null) {
          divBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.secretflow.spec.v1.Div, com.secretflow.spec.v1.Div.Builder, com.secretflow.spec.v1.DivOrBuilder>(
                  getDiv(),
                  getParentForChildren(),
                  isClean());
          div_ = null;
        }
        return divBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:secretflow.spec.v1.Div.Child)
    }

    // @@protoc_insertion_point(class_scope:secretflow.spec.v1.Div.Child)
    private static final com.secretflow.spec.v1.Div.Child DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.secretflow.spec.v1.Div.Child();
    }

    public static com.secretflow.spec.v1.Div.Child getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Child>
        PARSER = new com.google.protobuf.AbstractParser<Child>() {
      @java.lang.Override
      public Child parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Child> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Child> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.Div.Child getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Name of the Div.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the Div.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESC_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object desc_ = "";
  /**
   * <code>string desc = 2;</code>
   * @return The desc.
   */
  @java.lang.Override
  public java.lang.String getDesc() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      desc_ = s;
      return s;
    }
  }
  /**
   * <code>string desc = 2;</code>
   * @return The bytes for desc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescBytes() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      desc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHILDREN_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.secretflow.spec.v1.Div.Child> children_;
  /**
   * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.secretflow.spec.v1.Div.Child> getChildrenList() {
    return children_;
  }
  /**
   * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.secretflow.spec.v1.Div.ChildOrBuilder> 
      getChildrenOrBuilderList() {
    return children_;
  }
  /**
   * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
   */
  @java.lang.Override
  public int getChildrenCount() {
    return children_.size();
  }
  /**
   * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.Div.Child getChildren(int index) {
    return children_.get(index);
  }
  /**
   * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.Div.ChildOrBuilder getChildrenOrBuilder(
      int index) {
    return children_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(desc_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
    }
    for (int i = 0; i < children_.size(); i++) {
      output.writeMessage(3, children_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(desc_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
    }
    for (int i = 0; i < children_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, children_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.secretflow.spec.v1.Div)) {
      return super.equals(obj);
    }
    com.secretflow.spec.v1.Div other = (com.secretflow.spec.v1.Div) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getDesc()
        .equals(other.getDesc())) return false;
    if (!getChildrenList()
        .equals(other.getChildrenList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESC_FIELD_NUMBER;
    hash = (53 * hash) + getDesc().hashCode();
    if (getChildrenCount() > 0) {
      hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
      hash = (53 * hash) + getChildrenList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.secretflow.spec.v1.Div parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.Div parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Div parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.Div parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Div parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.Div parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Div parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.Div parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Div parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.Div parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Div parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.Div parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.secretflow.spec.v1.Div prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A division or a section of a page.
   * </pre>
   *
   * Protobuf type {@code secretflow.spec.v1.Div}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:secretflow.spec.v1.Div)
      com.secretflow.spec.v1.DivOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Div_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Div_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secretflow.spec.v1.Div.class, com.secretflow.spec.v1.Div.Builder.class);
    }

    // Construct using com.secretflow.spec.v1.Div.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      desc_ = "";
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
      } else {
        children_ = null;
        childrenBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Div_descriptor;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.Div getDefaultInstanceForType() {
      return com.secretflow.spec.v1.Div.getDefaultInstance();
    }

    @java.lang.Override
    public com.secretflow.spec.v1.Div build() {
      com.secretflow.spec.v1.Div result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.Div buildPartial() {
      com.secretflow.spec.v1.Div result = new com.secretflow.spec.v1.Div(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.secretflow.spec.v1.Div result) {
      if (childrenBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          children_ = java.util.Collections.unmodifiableList(children_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.children_ = children_;
      } else {
        result.children_ = childrenBuilder_.build();
      }
    }

    private void buildPartial0(com.secretflow.spec.v1.Div result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.desc_ = desc_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.secretflow.spec.v1.Div) {
        return mergeFrom((com.secretflow.spec.v1.Div)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.secretflow.spec.v1.Div other) {
      if (other == com.secretflow.spec.v1.Div.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDesc().isEmpty()) {
        desc_ = other.desc_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (childrenBuilder_ == null) {
        if (!other.children_.isEmpty()) {
          if (children_.isEmpty()) {
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureChildrenIsMutable();
            children_.addAll(other.children_);
          }
          onChanged();
        }
      } else {
        if (!other.children_.isEmpty()) {
          if (childrenBuilder_.isEmpty()) {
            childrenBuilder_.dispose();
            childrenBuilder_ = null;
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000004);
            childrenBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChildrenFieldBuilder() : null;
          } else {
            childrenBuilder_.addAllMessages(other.children_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              desc_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.secretflow.spec.v1.Div.Child m =
                  input.readMessage(
                      com.secretflow.spec.v1.Div.Child.parser(),
                      extensionRegistry);
              if (childrenBuilder_ == null) {
                ensureChildrenIsMutable();
                children_.add(m);
              } else {
                childrenBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Name of the Div.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the Div.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the Div.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Div.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Div.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object desc_ = "";
    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string desc = 2;</code>
     * @param value The desc to set.
     * @return This builder for chaining.
     */
    public Builder setDesc(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      desc_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDesc() {
      desc_ = getDefaultInstance().getDesc();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 2;</code>
     * @param value The bytes for desc to set.
     * @return This builder for chaining.
     */
    public Builder setDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      desc_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<com.secretflow.spec.v1.Div.Child> children_ =
      java.util.Collections.emptyList();
    private void ensureChildrenIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        children_ = new java.util.ArrayList<com.secretflow.spec.v1.Div.Child>(children_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.Div.Child, com.secretflow.spec.v1.Div.Child.Builder, com.secretflow.spec.v1.Div.ChildOrBuilder> childrenBuilder_;

    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public java.util.List<com.secretflow.spec.v1.Div.Child> getChildrenList() {
      if (childrenBuilder_ == null) {
        return java.util.Collections.unmodifiableList(children_);
      } else {
        return childrenBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public int getChildrenCount() {
      if (childrenBuilder_ == null) {
        return children_.size();
      } else {
        return childrenBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public com.secretflow.spec.v1.Div.Child getChildren(int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);
      } else {
        return childrenBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public Builder setChildren(
        int index, com.secretflow.spec.v1.Div.Child value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.set(index, value);
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public Builder setChildren(
        int index, com.secretflow.spec.v1.Div.Child.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.set(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public Builder addChildren(com.secretflow.spec.v1.Div.Child value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public Builder addChildren(
        int index, com.secretflow.spec.v1.Div.Child value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(index, value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public Builder addChildren(
        com.secretflow.spec.v1.Div.Child.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public Builder addChildren(
        int index, com.secretflow.spec.v1.Div.Child.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public Builder addAllChildren(
        java.lang.Iterable<? extends com.secretflow.spec.v1.Div.Child> values) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, children_);
        onChanged();
      } else {
        childrenBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public Builder clearChildren() {
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        childrenBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public Builder removeChildren(int index) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.remove(index);
        onChanged();
      } else {
        childrenBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public com.secretflow.spec.v1.Div.Child.Builder getChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public com.secretflow.spec.v1.Div.ChildOrBuilder getChildrenOrBuilder(
        int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);  } else {
        return childrenBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public java.util.List<? extends com.secretflow.spec.v1.Div.ChildOrBuilder> 
         getChildrenOrBuilderList() {
      if (childrenBuilder_ != null) {
        return childrenBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(children_);
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public com.secretflow.spec.v1.Div.Child.Builder addChildrenBuilder() {
      return getChildrenFieldBuilder().addBuilder(
          com.secretflow.spec.v1.Div.Child.getDefaultInstance());
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public com.secretflow.spec.v1.Div.Child.Builder addChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().addBuilder(
          index, com.secretflow.spec.v1.Div.Child.getDefaultInstance());
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div.Child children = 3;</code>
     */
    public java.util.List<com.secretflow.spec.v1.Div.Child.Builder> 
         getChildrenBuilderList() {
      return getChildrenFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.Div.Child, com.secretflow.spec.v1.Div.Child.Builder, com.secretflow.spec.v1.Div.ChildOrBuilder> 
        getChildrenFieldBuilder() {
      if (childrenBuilder_ == null) {
        childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.secretflow.spec.v1.Div.Child, com.secretflow.spec.v1.Div.Child.Builder, com.secretflow.spec.v1.Div.ChildOrBuilder>(
                children_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        children_ = null;
      }
      return childrenBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:secretflow.spec.v1.Div)
  }

  // @@protoc_insertion_point(class_scope:secretflow.spec.v1.Div)
  private static final com.secretflow.spec.v1.Div DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.secretflow.spec.v1.Div();
  }

  public static com.secretflow.spec.v1.Div getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Div>
      PARSER = new com.google.protobuf.AbstractParser<Div>() {
    @java.lang.Override
    public Div parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Div> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Div> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.secretflow.spec.v1.Div getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

