// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/spec/v1/data.proto

package com.secretflow.spec.v1;

/**
 * <pre>
 * IndividualTable describes a table owned by a single party.
 * </pre>
 *
 * Protobuf type {@code secretflow.spec.v1.IndividualTable}
 */
public final class IndividualTable extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:secretflow.spec.v1.IndividualTable)
    IndividualTableOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IndividualTable.newBuilder() to construct.
  private IndividualTable(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IndividualTable() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IndividualTable();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.secretflow.spec.v1.DataProto.internal_static_secretflow_spec_v1_IndividualTable_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.secretflow.spec.v1.DataProto.internal_static_secretflow_spec_v1_IndividualTable_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.secretflow.spec.v1.IndividualTable.class, com.secretflow.spec.v1.IndividualTable.Builder.class);
  }

  public static final int SCHEMA_FIELD_NUMBER = 1;
  private com.secretflow.spec.v1.TableSchema schema_;
  /**
   * <pre>
   * Schema.
   * </pre>
   *
   * <code>.secretflow.spec.v1.TableSchema schema = 1;</code>
   * @return Whether the schema field is set.
   */
  @java.lang.Override
  public boolean hasSchema() {
    return schema_ != null;
  }
  /**
   * <pre>
   * Schema.
   * </pre>
   *
   * <code>.secretflow.spec.v1.TableSchema schema = 1;</code>
   * @return The schema.
   */
  @java.lang.Override
  public com.secretflow.spec.v1.TableSchema getSchema() {
    return schema_ == null ? com.secretflow.spec.v1.TableSchema.getDefaultInstance() : schema_;
  }
  /**
   * <pre>
   * Schema.
   * </pre>
   *
   * <code>.secretflow.spec.v1.TableSchema schema = 1;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.TableSchemaOrBuilder getSchemaOrBuilder() {
    return schema_ == null ? com.secretflow.spec.v1.TableSchema.getDefaultInstance() : schema_;
  }

  public static final int LINE_COUNT_FIELD_NUMBER = 2;
  private long lineCount_ = 0L;
  /**
   * <pre>
   * If -1, the number is unknown.
   * </pre>
   *
   * <code>int64 line_count = 2;</code>
   * @return The lineCount.
   */
  @java.lang.Override
  public long getLineCount() {
    return lineCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (schema_ != null) {
      output.writeMessage(1, getSchema());
    }
    if (lineCount_ != 0L) {
      output.writeInt64(2, lineCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (schema_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSchema());
    }
    if (lineCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, lineCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.secretflow.spec.v1.IndividualTable)) {
      return super.equals(obj);
    }
    com.secretflow.spec.v1.IndividualTable other = (com.secretflow.spec.v1.IndividualTable) obj;

    if (hasSchema() != other.hasSchema()) return false;
    if (hasSchema()) {
      if (!getSchema()
          .equals(other.getSchema())) return false;
    }
    if (getLineCount()
        != other.getLineCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSchema()) {
      hash = (37 * hash) + SCHEMA_FIELD_NUMBER;
      hash = (53 * hash) + getSchema().hashCode();
    }
    hash = (37 * hash) + LINE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLineCount());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.secretflow.spec.v1.IndividualTable parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.IndividualTable parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.IndividualTable parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.IndividualTable parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.IndividualTable parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.IndividualTable parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.IndividualTable parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.IndividualTable parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.IndividualTable parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.IndividualTable parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.IndividualTable parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.IndividualTable parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.secretflow.spec.v1.IndividualTable prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * IndividualTable describes a table owned by a single party.
   * </pre>
   *
   * Protobuf type {@code secretflow.spec.v1.IndividualTable}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:secretflow.spec.v1.IndividualTable)
      com.secretflow.spec.v1.IndividualTableOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secretflow.spec.v1.DataProto.internal_static_secretflow_spec_v1_IndividualTable_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secretflow.spec.v1.DataProto.internal_static_secretflow_spec_v1_IndividualTable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secretflow.spec.v1.IndividualTable.class, com.secretflow.spec.v1.IndividualTable.Builder.class);
    }

    // Construct using com.secretflow.spec.v1.IndividualTable.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      schema_ = null;
      if (schemaBuilder_ != null) {
        schemaBuilder_.dispose();
        schemaBuilder_ = null;
      }
      lineCount_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.secretflow.spec.v1.DataProto.internal_static_secretflow_spec_v1_IndividualTable_descriptor;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.IndividualTable getDefaultInstanceForType() {
      return com.secretflow.spec.v1.IndividualTable.getDefaultInstance();
    }

    @java.lang.Override
    public com.secretflow.spec.v1.IndividualTable build() {
      com.secretflow.spec.v1.IndividualTable result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.IndividualTable buildPartial() {
      com.secretflow.spec.v1.IndividualTable result = new com.secretflow.spec.v1.IndividualTable(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.secretflow.spec.v1.IndividualTable result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.schema_ = schemaBuilder_ == null
            ? schema_
            : schemaBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.lineCount_ = lineCount_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.secretflow.spec.v1.IndividualTable) {
        return mergeFrom((com.secretflow.spec.v1.IndividualTable)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.secretflow.spec.v1.IndividualTable other) {
      if (other == com.secretflow.spec.v1.IndividualTable.getDefaultInstance()) return this;
      if (other.hasSchema()) {
        mergeSchema(other.getSchema());
      }
      if (other.getLineCount() != 0L) {
        setLineCount(other.getLineCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getSchemaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              lineCount_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.secretflow.spec.v1.TableSchema schema_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.secretflow.spec.v1.TableSchema, com.secretflow.spec.v1.TableSchema.Builder, com.secretflow.spec.v1.TableSchemaOrBuilder> schemaBuilder_;
    /**
     * <pre>
     * Schema.
     * </pre>
     *
     * <code>.secretflow.spec.v1.TableSchema schema = 1;</code>
     * @return Whether the schema field is set.
     */
    public boolean hasSchema() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Schema.
     * </pre>
     *
     * <code>.secretflow.spec.v1.TableSchema schema = 1;</code>
     * @return The schema.
     */
    public com.secretflow.spec.v1.TableSchema getSchema() {
      if (schemaBuilder_ == null) {
        return schema_ == null ? com.secretflow.spec.v1.TableSchema.getDefaultInstance() : schema_;
      } else {
        return schemaBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Schema.
     * </pre>
     *
     * <code>.secretflow.spec.v1.TableSchema schema = 1;</code>
     */
    public Builder setSchema(com.secretflow.spec.v1.TableSchema value) {
      if (schemaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        schema_ = value;
      } else {
        schemaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Schema.
     * </pre>
     *
     * <code>.secretflow.spec.v1.TableSchema schema = 1;</code>
     */
    public Builder setSchema(
        com.secretflow.spec.v1.TableSchema.Builder builderForValue) {
      if (schemaBuilder_ == null) {
        schema_ = builderForValue.build();
      } else {
        schemaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Schema.
     * </pre>
     *
     * <code>.secretflow.spec.v1.TableSchema schema = 1;</code>
     */
    public Builder mergeSchema(com.secretflow.spec.v1.TableSchema value) {
      if (schemaBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          schema_ != null &&
          schema_ != com.secretflow.spec.v1.TableSchema.getDefaultInstance()) {
          getSchemaBuilder().mergeFrom(value);
        } else {
          schema_ = value;
        }
      } else {
        schemaBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Schema.
     * </pre>
     *
     * <code>.secretflow.spec.v1.TableSchema schema = 1;</code>
     */
    public Builder clearSchema() {
      bitField0_ = (bitField0_ & ~0x00000001);
      schema_ = null;
      if (schemaBuilder_ != null) {
        schemaBuilder_.dispose();
        schemaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Schema.
     * </pre>
     *
     * <code>.secretflow.spec.v1.TableSchema schema = 1;</code>
     */
    public com.secretflow.spec.v1.TableSchema.Builder getSchemaBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getSchemaFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Schema.
     * </pre>
     *
     * <code>.secretflow.spec.v1.TableSchema schema = 1;</code>
     */
    public com.secretflow.spec.v1.TableSchemaOrBuilder getSchemaOrBuilder() {
      if (schemaBuilder_ != null) {
        return schemaBuilder_.getMessageOrBuilder();
      } else {
        return schema_ == null ?
            com.secretflow.spec.v1.TableSchema.getDefaultInstance() : schema_;
      }
    }
    /**
     * <pre>
     * Schema.
     * </pre>
     *
     * <code>.secretflow.spec.v1.TableSchema schema = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.secretflow.spec.v1.TableSchema, com.secretflow.spec.v1.TableSchema.Builder, com.secretflow.spec.v1.TableSchemaOrBuilder> 
        getSchemaFieldBuilder() {
      if (schemaBuilder_ == null) {
        schemaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.secretflow.spec.v1.TableSchema, com.secretflow.spec.v1.TableSchema.Builder, com.secretflow.spec.v1.TableSchemaOrBuilder>(
                getSchema(),
                getParentForChildren(),
                isClean());
        schema_ = null;
      }
      return schemaBuilder_;
    }

    private long lineCount_ ;
    /**
     * <pre>
     * If -1, the number is unknown.
     * </pre>
     *
     * <code>int64 line_count = 2;</code>
     * @return The lineCount.
     */
    @java.lang.Override
    public long getLineCount() {
      return lineCount_;
    }
    /**
     * <pre>
     * If -1, the number is unknown.
     * </pre>
     *
     * <code>int64 line_count = 2;</code>
     * @param value The lineCount to set.
     * @return This builder for chaining.
     */
    public Builder setLineCount(long value) {

      lineCount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If -1, the number is unknown.
     * </pre>
     *
     * <code>int64 line_count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLineCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      lineCount_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:secretflow.spec.v1.IndividualTable)
  }

  // @@protoc_insertion_point(class_scope:secretflow.spec.v1.IndividualTable)
  private static final com.secretflow.spec.v1.IndividualTable DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.secretflow.spec.v1.IndividualTable();
  }

  public static com.secretflow.spec.v1.IndividualTable getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IndividualTable>
      PARSER = new com.google.protobuf.AbstractParser<IndividualTable>() {
    @java.lang.Override
    public IndividualTable parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IndividualTable> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IndividualTable> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.secretflow.spec.v1.IndividualTable getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

