// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/spec/v1/component.proto

package com.secretflow.spec.v1;

/**
 * <pre>
 * Define an input/output for component.
 * </pre>
 *
 * Protobuf type {@code secretflow.spec.v1.IoDef}
 */
public final class IoDef extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:secretflow.spec.v1.IoDef)
    IoDefOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IoDef.newBuilder() to construct.
  private IoDef(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IoDef() {
    name_ = "";
    desc_ = "";
    types_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    attrs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IoDef();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_IoDef_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_IoDef_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.secretflow.spec.v1.IoDef.class, com.secretflow.spec.v1.IoDef.Builder.class);
  }

  public interface TableAttrDefOrBuilder extends
      // @@protoc_insertion_point(interface_extends:secretflow.spec.v1.IoDef.TableAttrDef)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Must be unique among all attributes for the table.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * Must be unique among all attributes for the table.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    java.lang.String getDesc();
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <pre>
     * Accepted col data types.
     * Please check comments of TableSchema in data.proto.
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @return A list containing the types.
     */
    java.util.List<java.lang.String>
        getTypesList();
    /**
     * <pre>
     * Accepted col data types.
     * Please check comments of TableSchema in data.proto.
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @return The count of types.
     */
    int getTypesCount();
    /**
     * <pre>
     * Accepted col data types.
     * Please check comments of TableSchema in data.proto.
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @param index The index of the element to return.
     * @return The types at the given index.
     */
    java.lang.String getTypes(int index);
    /**
     * <pre>
     * Accepted col data types.
     * Please check comments of TableSchema in data.proto.
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the types at the given index.
     */
    com.google.protobuf.ByteString
        getTypesBytes(int index);

    /**
     * <pre>
     * inclusive
     * </pre>
     *
     * <code>int64 col_min_cnt_inclusive = 4;</code>
     * @return The colMinCntInclusive.
     */
    long getColMinCntInclusive();

    /**
     * <code>int64 col_max_cnt_inclusive = 5;</code>
     * @return The colMaxCntInclusive.
     */
    long getColMaxCntInclusive();

    /**
     * <pre>
     * extra attribute for specified col.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
     */
    java.util.List<com.secretflow.spec.v1.AttributeDef> 
        getExtraAttrsList();
    /**
     * <pre>
     * extra attribute for specified col.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
     */
    com.secretflow.spec.v1.AttributeDef getExtraAttrs(int index);
    /**
     * <pre>
     * extra attribute for specified col.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
     */
    int getExtraAttrsCount();
    /**
     * <pre>
     * extra attribute for specified col.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
     */
    java.util.List<? extends com.secretflow.spec.v1.AttributeDefOrBuilder> 
        getExtraAttrsOrBuilderList();
    /**
     * <pre>
     * extra attribute for specified col.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
     */
    com.secretflow.spec.v1.AttributeDefOrBuilder getExtraAttrsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * An extra attribute for a table.
   *
   * If provided in a IoDef, e.g.
   * ```json
   * {
   *   "name": "feature",
   *   "types": [
   *       "int",
   *       "float"
   *   ],
   *   "col_min_cnt_inclusive": 1,
   *   "col_max_cnt": 3,
   *   "attrs": [
   *       {
   *           "name": "bucket_size",
   *           "type": "AT_INT"
   *       }
   *   ]
   * }
   * ```
   * means after a user provide a table as IO, they should also specify
   * cols as "feature":
   * - col_min_cnt_inclusive is 1: At least 1 col to be selected.
   * - col_max_cnt_inclusive is 3: At most 3 cols to be selected.
   * And afterwards, user have to fill an int attribute called bucket_size for
   * each selected cols.
   * </pre>
   *
   * Protobuf type {@code secretflow.spec.v1.IoDef.TableAttrDef}
   */
  public static final class TableAttrDef extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:secretflow.spec.v1.IoDef.TableAttrDef)
      TableAttrDefOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TableAttrDef.newBuilder() to construct.
    private TableAttrDef(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TableAttrDef() {
      name_ = "";
      desc_ = "";
      types_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      extraAttrs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TableAttrDef();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_IoDef_TableAttrDef_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_IoDef_TableAttrDef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secretflow.spec.v1.IoDef.TableAttrDef.class, com.secretflow.spec.v1.IoDef.TableAttrDef.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     * Must be unique among all attributes for the table.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Must be unique among all attributes for the table.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object desc_ = "";
    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    @java.lang.Override
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList types_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * Accepted col data types.
     * Please check comments of TableSchema in data.proto.
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @return A list containing the types.
     */
    public com.google.protobuf.ProtocolStringList
        getTypesList() {
      return types_;
    }
    /**
     * <pre>
     * Accepted col data types.
     * Please check comments of TableSchema in data.proto.
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @return The count of types.
     */
    public int getTypesCount() {
      return types_.size();
    }
    /**
     * <pre>
     * Accepted col data types.
     * Please check comments of TableSchema in data.proto.
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @param index The index of the element to return.
     * @return The types at the given index.
     */
    public java.lang.String getTypes(int index) {
      return types_.get(index);
    }
    /**
     * <pre>
     * Accepted col data types.
     * Please check comments of TableSchema in data.proto.
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the types at the given index.
     */
    public com.google.protobuf.ByteString
        getTypesBytes(int index) {
      return types_.getByteString(index);
    }

    public static final int COL_MIN_CNT_INCLUSIVE_FIELD_NUMBER = 4;
    private long colMinCntInclusive_ = 0L;
    /**
     * <pre>
     * inclusive
     * </pre>
     *
     * <code>int64 col_min_cnt_inclusive = 4;</code>
     * @return The colMinCntInclusive.
     */
    @java.lang.Override
    public long getColMinCntInclusive() {
      return colMinCntInclusive_;
    }

    public static final int COL_MAX_CNT_INCLUSIVE_FIELD_NUMBER = 5;
    private long colMaxCntInclusive_ = 0L;
    /**
     * <code>int64 col_max_cnt_inclusive = 5;</code>
     * @return The colMaxCntInclusive.
     */
    @java.lang.Override
    public long getColMaxCntInclusive() {
      return colMaxCntInclusive_;
    }

    public static final int EXTRA_ATTRS_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private java.util.List<com.secretflow.spec.v1.AttributeDef> extraAttrs_;
    /**
     * <pre>
     * extra attribute for specified col.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
     */
    @java.lang.Override
    public java.util.List<com.secretflow.spec.v1.AttributeDef> getExtraAttrsList() {
      return extraAttrs_;
    }
    /**
     * <pre>
     * extra attribute for specified col.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.secretflow.spec.v1.AttributeDefOrBuilder> 
        getExtraAttrsOrBuilderList() {
      return extraAttrs_;
    }
    /**
     * <pre>
     * extra attribute for specified col.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
     */
    @java.lang.Override
    public int getExtraAttrsCount() {
      return extraAttrs_.size();
    }
    /**
     * <pre>
     * extra attribute for specified col.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
     */
    @java.lang.Override
    public com.secretflow.spec.v1.AttributeDef getExtraAttrs(int index) {
      return extraAttrs_.get(index);
    }
    /**
     * <pre>
     * extra attribute for specified col.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
     */
    @java.lang.Override
    public com.secretflow.spec.v1.AttributeDefOrBuilder getExtraAttrsOrBuilder(
        int index) {
      return extraAttrs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(desc_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
      }
      for (int i = 0; i < types_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, types_.getRaw(i));
      }
      if (colMinCntInclusive_ != 0L) {
        output.writeInt64(4, colMinCntInclusive_);
      }
      if (colMaxCntInclusive_ != 0L) {
        output.writeInt64(5, colMaxCntInclusive_);
      }
      for (int i = 0; i < extraAttrs_.size(); i++) {
        output.writeMessage(6, extraAttrs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(desc_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < types_.size(); i++) {
          dataSize += computeStringSizeNoTag(types_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTypesList().size();
      }
      if (colMinCntInclusive_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, colMinCntInclusive_);
      }
      if (colMaxCntInclusive_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, colMaxCntInclusive_);
      }
      for (int i = 0; i < extraAttrs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, extraAttrs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.secretflow.spec.v1.IoDef.TableAttrDef)) {
        return super.equals(obj);
      }
      com.secretflow.spec.v1.IoDef.TableAttrDef other = (com.secretflow.spec.v1.IoDef.TableAttrDef) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getDesc()
          .equals(other.getDesc())) return false;
      if (!getTypesList()
          .equals(other.getTypesList())) return false;
      if (getColMinCntInclusive()
          != other.getColMinCntInclusive()) return false;
      if (getColMaxCntInclusive()
          != other.getColMaxCntInclusive()) return false;
      if (!getExtraAttrsList()
          .equals(other.getExtraAttrsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      if (getTypesCount() > 0) {
        hash = (37 * hash) + TYPES_FIELD_NUMBER;
        hash = (53 * hash) + getTypesList().hashCode();
      }
      hash = (37 * hash) + COL_MIN_CNT_INCLUSIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getColMinCntInclusive());
      hash = (37 * hash) + COL_MAX_CNT_INCLUSIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getColMaxCntInclusive());
      if (getExtraAttrsCount() > 0) {
        hash = (37 * hash) + EXTRA_ATTRS_FIELD_NUMBER;
        hash = (53 * hash) + getExtraAttrsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.secretflow.spec.v1.IoDef.TableAttrDef parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secretflow.spec.v1.IoDef.TableAttrDef parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secretflow.spec.v1.IoDef.TableAttrDef parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secretflow.spec.v1.IoDef.TableAttrDef parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secretflow.spec.v1.IoDef.TableAttrDef parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secretflow.spec.v1.IoDef.TableAttrDef parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secretflow.spec.v1.IoDef.TableAttrDef parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.secretflow.spec.v1.IoDef.TableAttrDef parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.secretflow.spec.v1.IoDef.TableAttrDef parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.secretflow.spec.v1.IoDef.TableAttrDef parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.secretflow.spec.v1.IoDef.TableAttrDef parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.secretflow.spec.v1.IoDef.TableAttrDef parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.secretflow.spec.v1.IoDef.TableAttrDef prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * An extra attribute for a table.
     *
     * If provided in a IoDef, e.g.
     * ```json
     * {
     *   "name": "feature",
     *   "types": [
     *       "int",
     *       "float"
     *   ],
     *   "col_min_cnt_inclusive": 1,
     *   "col_max_cnt": 3,
     *   "attrs": [
     *       {
     *           "name": "bucket_size",
     *           "type": "AT_INT"
     *       }
     *   ]
     * }
     * ```
     * means after a user provide a table as IO, they should also specify
     * cols as "feature":
     * - col_min_cnt_inclusive is 1: At least 1 col to be selected.
     * - col_max_cnt_inclusive is 3: At most 3 cols to be selected.
     * And afterwards, user have to fill an int attribute called bucket_size for
     * each selected cols.
     * </pre>
     *
     * Protobuf type {@code secretflow.spec.v1.IoDef.TableAttrDef}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:secretflow.spec.v1.IoDef.TableAttrDef)
        com.secretflow.spec.v1.IoDef.TableAttrDefOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_IoDef_TableAttrDef_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_IoDef_TableAttrDef_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.secretflow.spec.v1.IoDef.TableAttrDef.class, com.secretflow.spec.v1.IoDef.TableAttrDef.Builder.class);
      }

      // Construct using com.secretflow.spec.v1.IoDef.TableAttrDef.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        desc_ = "";
        types_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        colMinCntInclusive_ = 0L;
        colMaxCntInclusive_ = 0L;
        if (extraAttrsBuilder_ == null) {
          extraAttrs_ = java.util.Collections.emptyList();
        } else {
          extraAttrs_ = null;
          extraAttrsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_IoDef_TableAttrDef_descriptor;
      }

      @java.lang.Override
      public com.secretflow.spec.v1.IoDef.TableAttrDef getDefaultInstanceForType() {
        return com.secretflow.spec.v1.IoDef.TableAttrDef.getDefaultInstance();
      }

      @java.lang.Override
      public com.secretflow.spec.v1.IoDef.TableAttrDef build() {
        com.secretflow.spec.v1.IoDef.TableAttrDef result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.secretflow.spec.v1.IoDef.TableAttrDef buildPartial() {
        com.secretflow.spec.v1.IoDef.TableAttrDef result = new com.secretflow.spec.v1.IoDef.TableAttrDef(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.secretflow.spec.v1.IoDef.TableAttrDef result) {
        if (extraAttrsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0)) {
            extraAttrs_ = java.util.Collections.unmodifiableList(extraAttrs_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.extraAttrs_ = extraAttrs_;
        } else {
          result.extraAttrs_ = extraAttrsBuilder_.build();
        }
      }

      private void buildPartial0(com.secretflow.spec.v1.IoDef.TableAttrDef result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.desc_ = desc_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          types_.makeImmutable();
          result.types_ = types_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.colMinCntInclusive_ = colMinCntInclusive_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.colMaxCntInclusive_ = colMaxCntInclusive_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.secretflow.spec.v1.IoDef.TableAttrDef) {
          return mergeFrom((com.secretflow.spec.v1.IoDef.TableAttrDef)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.secretflow.spec.v1.IoDef.TableAttrDef other) {
        if (other == com.secretflow.spec.v1.IoDef.TableAttrDef.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.types_.isEmpty()) {
          if (types_.isEmpty()) {
            types_ = other.types_;
            bitField0_ |= 0x00000004;
          } else {
            ensureTypesIsMutable();
            types_.addAll(other.types_);
          }
          onChanged();
        }
        if (other.getColMinCntInclusive() != 0L) {
          setColMinCntInclusive(other.getColMinCntInclusive());
        }
        if (other.getColMaxCntInclusive() != 0L) {
          setColMaxCntInclusive(other.getColMaxCntInclusive());
        }
        if (extraAttrsBuilder_ == null) {
          if (!other.extraAttrs_.isEmpty()) {
            if (extraAttrs_.isEmpty()) {
              extraAttrs_ = other.extraAttrs_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureExtraAttrsIsMutable();
              extraAttrs_.addAll(other.extraAttrs_);
            }
            onChanged();
          }
        } else {
          if (!other.extraAttrs_.isEmpty()) {
            if (extraAttrsBuilder_.isEmpty()) {
              extraAttrsBuilder_.dispose();
              extraAttrsBuilder_ = null;
              extraAttrs_ = other.extraAttrs_;
              bitField0_ = (bitField0_ & ~0x00000020);
              extraAttrsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getExtraAttrsFieldBuilder() : null;
            } else {
              extraAttrsBuilder_.addAllMessages(other.extraAttrs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                desc_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureTypesIsMutable();
                types_.add(s);
                break;
              } // case 26
              case 32: {
                colMinCntInclusive_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                colMaxCntInclusive_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                com.secretflow.spec.v1.AttributeDef m =
                    input.readMessage(
                        com.secretflow.spec.v1.AttributeDef.parser(),
                        extensionRegistry);
                if (extraAttrsBuilder_ == null) {
                  ensureExtraAttrsIsMutable();
                  extraAttrs_.add(m);
                } else {
                  extraAttrsBuilder_.addMessage(m);
                }
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * Must be unique among all attributes for the table.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Must be unique among all attributes for the table.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Must be unique among all attributes for the table.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Must be unique among all attributes for the table.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Must be unique among all attributes for the table.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>string desc = 2;</code>
       * @return The desc.
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string desc = 2;</code>
       * @return The bytes for desc.
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string desc = 2;</code>
       * @param value The desc to set.
       * @return This builder for chaining.
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        desc_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDesc() {
        desc_ = getDefaultInstance().getDesc();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 2;</code>
       * @param value The bytes for desc to set.
       * @return This builder for chaining.
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        desc_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList types_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureTypesIsMutable() {
        if (!types_.isModifiable()) {
          types_ = new com.google.protobuf.LazyStringArrayList(types_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <pre>
       * Accepted col data types.
       * Please check comments of TableSchema in data.proto.
       * </pre>
       *
       * <code>repeated string types = 3;</code>
       * @return A list containing the types.
       */
      public com.google.protobuf.ProtocolStringList
          getTypesList() {
        types_.makeImmutable();
        return types_;
      }
      /**
       * <pre>
       * Accepted col data types.
       * Please check comments of TableSchema in data.proto.
       * </pre>
       *
       * <code>repeated string types = 3;</code>
       * @return The count of types.
       */
      public int getTypesCount() {
        return types_.size();
      }
      /**
       * <pre>
       * Accepted col data types.
       * Please check comments of TableSchema in data.proto.
       * </pre>
       *
       * <code>repeated string types = 3;</code>
       * @param index The index of the element to return.
       * @return The types at the given index.
       */
      public java.lang.String getTypes(int index) {
        return types_.get(index);
      }
      /**
       * <pre>
       * Accepted col data types.
       * Please check comments of TableSchema in data.proto.
       * </pre>
       *
       * <code>repeated string types = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the types at the given index.
       */
      public com.google.protobuf.ByteString
          getTypesBytes(int index) {
        return types_.getByteString(index);
      }
      /**
       * <pre>
       * Accepted col data types.
       * Please check comments of TableSchema in data.proto.
       * </pre>
       *
       * <code>repeated string types = 3;</code>
       * @param index The index to set the value at.
       * @param value The types to set.
       * @return This builder for chaining.
       */
      public Builder setTypes(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureTypesIsMutable();
        types_.set(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Accepted col data types.
       * Please check comments of TableSchema in data.proto.
       * </pre>
       *
       * <code>repeated string types = 3;</code>
       * @param value The types to add.
       * @return This builder for chaining.
       */
      public Builder addTypes(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureTypesIsMutable();
        types_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Accepted col data types.
       * Please check comments of TableSchema in data.proto.
       * </pre>
       *
       * <code>repeated string types = 3;</code>
       * @param values The types to add.
       * @return This builder for chaining.
       */
      public Builder addAllTypes(
          java.lang.Iterable<java.lang.String> values) {
        ensureTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, types_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Accepted col data types.
       * Please check comments of TableSchema in data.proto.
       * </pre>
       *
       * <code>repeated string types = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypes() {
        types_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Accepted col data types.
       * Please check comments of TableSchema in data.proto.
       * </pre>
       *
       * <code>repeated string types = 3;</code>
       * @param value The bytes of the types to add.
       * @return This builder for chaining.
       */
      public Builder addTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureTypesIsMutable();
        types_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private long colMinCntInclusive_ ;
      /**
       * <pre>
       * inclusive
       * </pre>
       *
       * <code>int64 col_min_cnt_inclusive = 4;</code>
       * @return The colMinCntInclusive.
       */
      @java.lang.Override
      public long getColMinCntInclusive() {
        return colMinCntInclusive_;
      }
      /**
       * <pre>
       * inclusive
       * </pre>
       *
       * <code>int64 col_min_cnt_inclusive = 4;</code>
       * @param value The colMinCntInclusive to set.
       * @return This builder for chaining.
       */
      public Builder setColMinCntInclusive(long value) {

        colMinCntInclusive_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * inclusive
       * </pre>
       *
       * <code>int64 col_min_cnt_inclusive = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearColMinCntInclusive() {
        bitField0_ = (bitField0_ & ~0x00000008);
        colMinCntInclusive_ = 0L;
        onChanged();
        return this;
      }

      private long colMaxCntInclusive_ ;
      /**
       * <code>int64 col_max_cnt_inclusive = 5;</code>
       * @return The colMaxCntInclusive.
       */
      @java.lang.Override
      public long getColMaxCntInclusive() {
        return colMaxCntInclusive_;
      }
      /**
       * <code>int64 col_max_cnt_inclusive = 5;</code>
       * @param value The colMaxCntInclusive to set.
       * @return This builder for chaining.
       */
      public Builder setColMaxCntInclusive(long value) {

        colMaxCntInclusive_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 col_max_cnt_inclusive = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearColMaxCntInclusive() {
        bitField0_ = (bitField0_ & ~0x00000010);
        colMaxCntInclusive_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.secretflow.spec.v1.AttributeDef> extraAttrs_ =
        java.util.Collections.emptyList();
      private void ensureExtraAttrsIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          extraAttrs_ = new java.util.ArrayList<com.secretflow.spec.v1.AttributeDef>(extraAttrs_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.secretflow.spec.v1.AttributeDef, com.secretflow.spec.v1.AttributeDef.Builder, com.secretflow.spec.v1.AttributeDefOrBuilder> extraAttrsBuilder_;

      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public java.util.List<com.secretflow.spec.v1.AttributeDef> getExtraAttrsList() {
        if (extraAttrsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(extraAttrs_);
        } else {
          return extraAttrsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public int getExtraAttrsCount() {
        if (extraAttrsBuilder_ == null) {
          return extraAttrs_.size();
        } else {
          return extraAttrsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public com.secretflow.spec.v1.AttributeDef getExtraAttrs(int index) {
        if (extraAttrsBuilder_ == null) {
          return extraAttrs_.get(index);
        } else {
          return extraAttrsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public Builder setExtraAttrs(
          int index, com.secretflow.spec.v1.AttributeDef value) {
        if (extraAttrsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtraAttrsIsMutable();
          extraAttrs_.set(index, value);
          onChanged();
        } else {
          extraAttrsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public Builder setExtraAttrs(
          int index, com.secretflow.spec.v1.AttributeDef.Builder builderForValue) {
        if (extraAttrsBuilder_ == null) {
          ensureExtraAttrsIsMutable();
          extraAttrs_.set(index, builderForValue.build());
          onChanged();
        } else {
          extraAttrsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public Builder addExtraAttrs(com.secretflow.spec.v1.AttributeDef value) {
        if (extraAttrsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtraAttrsIsMutable();
          extraAttrs_.add(value);
          onChanged();
        } else {
          extraAttrsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public Builder addExtraAttrs(
          int index, com.secretflow.spec.v1.AttributeDef value) {
        if (extraAttrsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtraAttrsIsMutable();
          extraAttrs_.add(index, value);
          onChanged();
        } else {
          extraAttrsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public Builder addExtraAttrs(
          com.secretflow.spec.v1.AttributeDef.Builder builderForValue) {
        if (extraAttrsBuilder_ == null) {
          ensureExtraAttrsIsMutable();
          extraAttrs_.add(builderForValue.build());
          onChanged();
        } else {
          extraAttrsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public Builder addExtraAttrs(
          int index, com.secretflow.spec.v1.AttributeDef.Builder builderForValue) {
        if (extraAttrsBuilder_ == null) {
          ensureExtraAttrsIsMutable();
          extraAttrs_.add(index, builderForValue.build());
          onChanged();
        } else {
          extraAttrsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public Builder addAllExtraAttrs(
          java.lang.Iterable<? extends com.secretflow.spec.v1.AttributeDef> values) {
        if (extraAttrsBuilder_ == null) {
          ensureExtraAttrsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, extraAttrs_);
          onChanged();
        } else {
          extraAttrsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public Builder clearExtraAttrs() {
        if (extraAttrsBuilder_ == null) {
          extraAttrs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          extraAttrsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public Builder removeExtraAttrs(int index) {
        if (extraAttrsBuilder_ == null) {
          ensureExtraAttrsIsMutable();
          extraAttrs_.remove(index);
          onChanged();
        } else {
          extraAttrsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public com.secretflow.spec.v1.AttributeDef.Builder getExtraAttrsBuilder(
          int index) {
        return getExtraAttrsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public com.secretflow.spec.v1.AttributeDefOrBuilder getExtraAttrsOrBuilder(
          int index) {
        if (extraAttrsBuilder_ == null) {
          return extraAttrs_.get(index);  } else {
          return extraAttrsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public java.util.List<? extends com.secretflow.spec.v1.AttributeDefOrBuilder> 
           getExtraAttrsOrBuilderList() {
        if (extraAttrsBuilder_ != null) {
          return extraAttrsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(extraAttrs_);
        }
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public com.secretflow.spec.v1.AttributeDef.Builder addExtraAttrsBuilder() {
        return getExtraAttrsFieldBuilder().addBuilder(
            com.secretflow.spec.v1.AttributeDef.getDefaultInstance());
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public com.secretflow.spec.v1.AttributeDef.Builder addExtraAttrsBuilder(
          int index) {
        return getExtraAttrsFieldBuilder().addBuilder(
            index, com.secretflow.spec.v1.AttributeDef.getDefaultInstance());
      }
      /**
       * <pre>
       * extra attribute for specified col.
       * </pre>
       *
       * <code>repeated .secretflow.spec.v1.AttributeDef extra_attrs = 6;</code>
       */
      public java.util.List<com.secretflow.spec.v1.AttributeDef.Builder> 
           getExtraAttrsBuilderList() {
        return getExtraAttrsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.secretflow.spec.v1.AttributeDef, com.secretflow.spec.v1.AttributeDef.Builder, com.secretflow.spec.v1.AttributeDefOrBuilder> 
          getExtraAttrsFieldBuilder() {
        if (extraAttrsBuilder_ == null) {
          extraAttrsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.secretflow.spec.v1.AttributeDef, com.secretflow.spec.v1.AttributeDef.Builder, com.secretflow.spec.v1.AttributeDefOrBuilder>(
                  extraAttrs_,
                  ((bitField0_ & 0x00000020) != 0),
                  getParentForChildren(),
                  isClean());
          extraAttrs_ = null;
        }
        return extraAttrsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:secretflow.spec.v1.IoDef.TableAttrDef)
    }

    // @@protoc_insertion_point(class_scope:secretflow.spec.v1.IoDef.TableAttrDef)
    private static final com.secretflow.spec.v1.IoDef.TableAttrDef DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.secretflow.spec.v1.IoDef.TableAttrDef();
    }

    public static com.secretflow.spec.v1.IoDef.TableAttrDef getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TableAttrDef>
        PARSER = new com.google.protobuf.AbstractParser<TableAttrDef>() {
      @java.lang.Override
      public TableAttrDef parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TableAttrDef> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TableAttrDef> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.IoDef.TableAttrDef getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * should be unique among all IOs of the component.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * should be unique among all IOs of the component.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESC_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object desc_ = "";
  /**
   * <code>string desc = 2;</code>
   * @return The desc.
   */
  @java.lang.Override
  public java.lang.String getDesc() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      desc_ = s;
      return s;
    }
  }
  /**
   * <code>string desc = 2;</code>
   * @return The bytes for desc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescBytes() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      desc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList types_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Must be one of DistData.type in data.proto
   * </pre>
   *
   * <code>repeated string types = 3;</code>
   * @return A list containing the types.
   */
  public com.google.protobuf.ProtocolStringList
      getTypesList() {
    return types_;
  }
  /**
   * <pre>
   * Must be one of DistData.type in data.proto
   * </pre>
   *
   * <code>repeated string types = 3;</code>
   * @return The count of types.
   */
  public int getTypesCount() {
    return types_.size();
  }
  /**
   * <pre>
   * Must be one of DistData.type in data.proto
   * </pre>
   *
   * <code>repeated string types = 3;</code>
   * @param index The index of the element to return.
   * @return The types at the given index.
   */
  public java.lang.String getTypes(int index) {
    return types_.get(index);
  }
  /**
   * <pre>
   * Must be one of DistData.type in data.proto
   * </pre>
   *
   * <code>repeated string types = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the types at the given index.
   */
  public com.google.protobuf.ByteString
      getTypesBytes(int index) {
    return types_.getByteString(index);
  }

  public static final int ATTRS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.secretflow.spec.v1.IoDef.TableAttrDef> attrs_;
  /**
   * <pre>
   * Only valid for tables.
   * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
   * name}/{TableAttrDef name}`.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.secretflow.spec.v1.IoDef.TableAttrDef> getAttrsList() {
    return attrs_;
  }
  /**
   * <pre>
   * Only valid for tables.
   * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
   * name}/{TableAttrDef name}`.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.secretflow.spec.v1.IoDef.TableAttrDefOrBuilder> 
      getAttrsOrBuilderList() {
    return attrs_;
  }
  /**
   * <pre>
   * Only valid for tables.
   * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
   * name}/{TableAttrDef name}`.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
   */
  @java.lang.Override
  public int getAttrsCount() {
    return attrs_.size();
  }
  /**
   * <pre>
   * Only valid for tables.
   * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
   * name}/{TableAttrDef name}`.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.IoDef.TableAttrDef getAttrs(int index) {
    return attrs_.get(index);
  }
  /**
   * <pre>
   * Only valid for tables.
   * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
   * name}/{TableAttrDef name}`.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.IoDef.TableAttrDefOrBuilder getAttrsOrBuilder(
      int index) {
    return attrs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(desc_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
    }
    for (int i = 0; i < types_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, types_.getRaw(i));
    }
    for (int i = 0; i < attrs_.size(); i++) {
      output.writeMessage(4, attrs_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(desc_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < types_.size(); i++) {
        dataSize += computeStringSizeNoTag(types_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTypesList().size();
    }
    for (int i = 0; i < attrs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, attrs_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.secretflow.spec.v1.IoDef)) {
      return super.equals(obj);
    }
    com.secretflow.spec.v1.IoDef other = (com.secretflow.spec.v1.IoDef) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getDesc()
        .equals(other.getDesc())) return false;
    if (!getTypesList()
        .equals(other.getTypesList())) return false;
    if (!getAttrsList()
        .equals(other.getAttrsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESC_FIELD_NUMBER;
    hash = (53 * hash) + getDesc().hashCode();
    if (getTypesCount() > 0) {
      hash = (37 * hash) + TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getTypesList().hashCode();
    }
    if (getAttrsCount() > 0) {
      hash = (37 * hash) + ATTRS_FIELD_NUMBER;
      hash = (53 * hash) + getAttrsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.secretflow.spec.v1.IoDef parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.IoDef parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.IoDef parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.IoDef parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.IoDef parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.IoDef parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.IoDef parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.IoDef parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.IoDef parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.IoDef parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.IoDef parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.IoDef parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.secretflow.spec.v1.IoDef prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Define an input/output for component.
   * </pre>
   *
   * Protobuf type {@code secretflow.spec.v1.IoDef}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:secretflow.spec.v1.IoDef)
      com.secretflow.spec.v1.IoDefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_IoDef_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_IoDef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secretflow.spec.v1.IoDef.class, com.secretflow.spec.v1.IoDef.Builder.class);
    }

    // Construct using com.secretflow.spec.v1.IoDef.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      desc_ = "";
      types_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (attrsBuilder_ == null) {
        attrs_ = java.util.Collections.emptyList();
      } else {
        attrs_ = null;
        attrsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.secretflow.spec.v1.ComponentProto.internal_static_secretflow_spec_v1_IoDef_descriptor;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.IoDef getDefaultInstanceForType() {
      return com.secretflow.spec.v1.IoDef.getDefaultInstance();
    }

    @java.lang.Override
    public com.secretflow.spec.v1.IoDef build() {
      com.secretflow.spec.v1.IoDef result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.IoDef buildPartial() {
      com.secretflow.spec.v1.IoDef result = new com.secretflow.spec.v1.IoDef(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.secretflow.spec.v1.IoDef result) {
      if (attrsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          attrs_ = java.util.Collections.unmodifiableList(attrs_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.attrs_ = attrs_;
      } else {
        result.attrs_ = attrsBuilder_.build();
      }
    }

    private void buildPartial0(com.secretflow.spec.v1.IoDef result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.desc_ = desc_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        types_.makeImmutable();
        result.types_ = types_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.secretflow.spec.v1.IoDef) {
        return mergeFrom((com.secretflow.spec.v1.IoDef)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.secretflow.spec.v1.IoDef other) {
      if (other == com.secretflow.spec.v1.IoDef.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDesc().isEmpty()) {
        desc_ = other.desc_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.types_.isEmpty()) {
        if (types_.isEmpty()) {
          types_ = other.types_;
          bitField0_ |= 0x00000004;
        } else {
          ensureTypesIsMutable();
          types_.addAll(other.types_);
        }
        onChanged();
      }
      if (attrsBuilder_ == null) {
        if (!other.attrs_.isEmpty()) {
          if (attrs_.isEmpty()) {
            attrs_ = other.attrs_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAttrsIsMutable();
            attrs_.addAll(other.attrs_);
          }
          onChanged();
        }
      } else {
        if (!other.attrs_.isEmpty()) {
          if (attrsBuilder_.isEmpty()) {
            attrsBuilder_.dispose();
            attrsBuilder_ = null;
            attrs_ = other.attrs_;
            bitField0_ = (bitField0_ & ~0x00000008);
            attrsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAttrsFieldBuilder() : null;
          } else {
            attrsBuilder_.addAllMessages(other.attrs_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              desc_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTypesIsMutable();
              types_.add(s);
              break;
            } // case 26
            case 34: {
              com.secretflow.spec.v1.IoDef.TableAttrDef m =
                  input.readMessage(
                      com.secretflow.spec.v1.IoDef.TableAttrDef.parser(),
                      extensionRegistry);
              if (attrsBuilder_ == null) {
                ensureAttrsIsMutable();
                attrs_.add(m);
              } else {
                attrsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * should be unique among all IOs of the component.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * should be unique among all IOs of the component.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * should be unique among all IOs of the component.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * should be unique among all IOs of the component.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * should be unique among all IOs of the component.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object desc_ = "";
    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string desc = 2;</code>
     * @param value The desc to set.
     * @return This builder for chaining.
     */
    public Builder setDesc(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      desc_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDesc() {
      desc_ = getDefaultInstance().getDesc();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 2;</code>
     * @param value The bytes for desc to set.
     * @return This builder for chaining.
     */
    public Builder setDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      desc_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList types_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTypesIsMutable() {
      if (!types_.isModifiable()) {
        types_ = new com.google.protobuf.LazyStringArrayList(types_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * Must be one of DistData.type in data.proto
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @return A list containing the types.
     */
    public com.google.protobuf.ProtocolStringList
        getTypesList() {
      types_.makeImmutable();
      return types_;
    }
    /**
     * <pre>
     * Must be one of DistData.type in data.proto
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @return The count of types.
     */
    public int getTypesCount() {
      return types_.size();
    }
    /**
     * <pre>
     * Must be one of DistData.type in data.proto
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @param index The index of the element to return.
     * @return The types at the given index.
     */
    public java.lang.String getTypes(int index) {
      return types_.get(index);
    }
    /**
     * <pre>
     * Must be one of DistData.type in data.proto
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the types at the given index.
     */
    public com.google.protobuf.ByteString
        getTypesBytes(int index) {
      return types_.getByteString(index);
    }
    /**
     * <pre>
     * Must be one of DistData.type in data.proto
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @param index The index to set the value at.
     * @param value The types to set.
     * @return This builder for chaining.
     */
    public Builder setTypes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTypesIsMutable();
      types_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Must be one of DistData.type in data.proto
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @param value The types to add.
     * @return This builder for chaining.
     */
    public Builder addTypes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTypesIsMutable();
      types_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Must be one of DistData.type in data.proto
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @param values The types to add.
     * @return This builder for chaining.
     */
    public Builder addAllTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, types_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Must be one of DistData.type in data.proto
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTypes() {
      types_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Must be one of DistData.type in data.proto
     * </pre>
     *
     * <code>repeated string types = 3;</code>
     * @param value The bytes of the types to add.
     * @return This builder for chaining.
     */
    public Builder addTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTypesIsMutable();
      types_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<com.secretflow.spec.v1.IoDef.TableAttrDef> attrs_ =
      java.util.Collections.emptyList();
    private void ensureAttrsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        attrs_ = new java.util.ArrayList<com.secretflow.spec.v1.IoDef.TableAttrDef>(attrs_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.IoDef.TableAttrDef, com.secretflow.spec.v1.IoDef.TableAttrDef.Builder, com.secretflow.spec.v1.IoDef.TableAttrDefOrBuilder> attrsBuilder_;

    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public java.util.List<com.secretflow.spec.v1.IoDef.TableAttrDef> getAttrsList() {
      if (attrsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attrs_);
      } else {
        return attrsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public int getAttrsCount() {
      if (attrsBuilder_ == null) {
        return attrs_.size();
      } else {
        return attrsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public com.secretflow.spec.v1.IoDef.TableAttrDef getAttrs(int index) {
      if (attrsBuilder_ == null) {
        return attrs_.get(index);
      } else {
        return attrsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public Builder setAttrs(
        int index, com.secretflow.spec.v1.IoDef.TableAttrDef value) {
      if (attrsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttrsIsMutable();
        attrs_.set(index, value);
        onChanged();
      } else {
        attrsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public Builder setAttrs(
        int index, com.secretflow.spec.v1.IoDef.TableAttrDef.Builder builderForValue) {
      if (attrsBuilder_ == null) {
        ensureAttrsIsMutable();
        attrs_.set(index, builderForValue.build());
        onChanged();
      } else {
        attrsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public Builder addAttrs(com.secretflow.spec.v1.IoDef.TableAttrDef value) {
      if (attrsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttrsIsMutable();
        attrs_.add(value);
        onChanged();
      } else {
        attrsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public Builder addAttrs(
        int index, com.secretflow.spec.v1.IoDef.TableAttrDef value) {
      if (attrsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttrsIsMutable();
        attrs_.add(index, value);
        onChanged();
      } else {
        attrsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public Builder addAttrs(
        com.secretflow.spec.v1.IoDef.TableAttrDef.Builder builderForValue) {
      if (attrsBuilder_ == null) {
        ensureAttrsIsMutable();
        attrs_.add(builderForValue.build());
        onChanged();
      } else {
        attrsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public Builder addAttrs(
        int index, com.secretflow.spec.v1.IoDef.TableAttrDef.Builder builderForValue) {
      if (attrsBuilder_ == null) {
        ensureAttrsIsMutable();
        attrs_.add(index, builderForValue.build());
        onChanged();
      } else {
        attrsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public Builder addAllAttrs(
        java.lang.Iterable<? extends com.secretflow.spec.v1.IoDef.TableAttrDef> values) {
      if (attrsBuilder_ == null) {
        ensureAttrsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attrs_);
        onChanged();
      } else {
        attrsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public Builder clearAttrs() {
      if (attrsBuilder_ == null) {
        attrs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        attrsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public Builder removeAttrs(int index) {
      if (attrsBuilder_ == null) {
        ensureAttrsIsMutable();
        attrs_.remove(index);
        onChanged();
      } else {
        attrsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public com.secretflow.spec.v1.IoDef.TableAttrDef.Builder getAttrsBuilder(
        int index) {
      return getAttrsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public com.secretflow.spec.v1.IoDef.TableAttrDefOrBuilder getAttrsOrBuilder(
        int index) {
      if (attrsBuilder_ == null) {
        return attrs_.get(index);  } else {
        return attrsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public java.util.List<? extends com.secretflow.spec.v1.IoDef.TableAttrDefOrBuilder> 
         getAttrsOrBuilderList() {
      if (attrsBuilder_ != null) {
        return attrsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attrs_);
      }
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public com.secretflow.spec.v1.IoDef.TableAttrDef.Builder addAttrsBuilder() {
      return getAttrsFieldBuilder().addBuilder(
          com.secretflow.spec.v1.IoDef.TableAttrDef.getDefaultInstance());
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public com.secretflow.spec.v1.IoDef.TableAttrDef.Builder addAttrsBuilder(
        int index) {
      return getAttrsFieldBuilder().addBuilder(
          index, com.secretflow.spec.v1.IoDef.TableAttrDef.getDefaultInstance());
    }
    /**
     * <pre>
     * Only valid for tables.
     * The attribute path for a TableAttrDef is `{input&#92;|output}/{IoDef
     * name}/{TableAttrDef name}`.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.IoDef.TableAttrDef attrs = 4;</code>
     */
    public java.util.List<com.secretflow.spec.v1.IoDef.TableAttrDef.Builder> 
         getAttrsBuilderList() {
      return getAttrsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.IoDef.TableAttrDef, com.secretflow.spec.v1.IoDef.TableAttrDef.Builder, com.secretflow.spec.v1.IoDef.TableAttrDefOrBuilder> 
        getAttrsFieldBuilder() {
      if (attrsBuilder_ == null) {
        attrsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.secretflow.spec.v1.IoDef.TableAttrDef, com.secretflow.spec.v1.IoDef.TableAttrDef.Builder, com.secretflow.spec.v1.IoDef.TableAttrDefOrBuilder>(
                attrs_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        attrs_ = null;
      }
      return attrsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:secretflow.spec.v1.IoDef)
  }

  // @@protoc_insertion_point(class_scope:secretflow.spec.v1.IoDef)
  private static final com.secretflow.spec.v1.IoDef DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.secretflow.spec.v1.IoDef();
  }

  public static com.secretflow.spec.v1.IoDef getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IoDef>
      PARSER = new com.google.protobuf.AbstractParser<IoDef>() {
    @java.lang.Override
    public IoDef parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IoDef> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IoDef> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.secretflow.spec.v1.IoDef getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

