// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/spec/v1/evaluation.proto

package com.secretflow.spec.v1;

/**
 * <pre>
 * Evaluate a node.
 * - CompListDef + StorageConfig + NodeEvalParam + other extra configs -&gt;
 * NodeEvalResult
 *
 * NodeEvalParam contains all the information to evaluate a component.
 * </pre>
 *
 * Protobuf type {@code secretflow.spec.v1.NodeEvalParam}
 */
public final class NodeEvalParam extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:secretflow.spec.v1.NodeEvalParam)
    NodeEvalParamOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NodeEvalParam.newBuilder() to construct.
  private NodeEvalParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NodeEvalParam() {
    domain_ = "";
    name_ = "";
    version_ = "";
    attrPaths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    attrs_ = java.util.Collections.emptyList();
    inputs_ = java.util.Collections.emptyList();
    outputUris_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NodeEvalParam();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.secretflow.spec.v1.EvaluationProto.internal_static_secretflow_spec_v1_NodeEvalParam_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.secretflow.spec.v1.EvaluationProto.internal_static_secretflow_spec_v1_NodeEvalParam_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.secretflow.spec.v1.NodeEvalParam.class, com.secretflow.spec.v1.NodeEvalParam.Builder.class);
  }

  public static final int DOMAIN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object domain_ = "";
  /**
   * <pre>
   * Domain of the component.
   * </pre>
   *
   * <code>string domain = 1;</code>
   * @return The domain.
   */
  @java.lang.Override
  public java.lang.String getDomain() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      domain_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Domain of the component.
   * </pre>
   *
   * <code>string domain = 1;</code>
   * @return The bytes for domain.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDomainBytes() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      domain_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Name of the component.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the component.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object version_ = "";
  /**
   * <pre>
   * Version of the component.
   * </pre>
   *
   * <code>string version = 3;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Version of the component.
   * </pre>
   *
   * <code>string version = 3;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTR_PATHS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList attrPaths_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * The path of attributes.
   * The attribute path for a TableAttrDef is `(input|output)/(IoDef
   * name)/(TableAttrDef name)(/(column name)(/(extra attributes))?)?`.
   * </pre>
   *
   * <code>repeated string attr_paths = 4;</code>
   * @return A list containing the attrPaths.
   */
  public com.google.protobuf.ProtocolStringList
      getAttrPathsList() {
    return attrPaths_;
  }
  /**
   * <pre>
   * The path of attributes.
   * The attribute path for a TableAttrDef is `(input|output)/(IoDef
   * name)/(TableAttrDef name)(/(column name)(/(extra attributes))?)?`.
   * </pre>
   *
   * <code>repeated string attr_paths = 4;</code>
   * @return The count of attrPaths.
   */
  public int getAttrPathsCount() {
    return attrPaths_.size();
  }
  /**
   * <pre>
   * The path of attributes.
   * The attribute path for a TableAttrDef is `(input|output)/(IoDef
   * name)/(TableAttrDef name)(/(column name)(/(extra attributes))?)?`.
   * </pre>
   *
   * <code>repeated string attr_paths = 4;</code>
   * @param index The index of the element to return.
   * @return The attrPaths at the given index.
   */
  public java.lang.String getAttrPaths(int index) {
    return attrPaths_.get(index);
  }
  /**
   * <pre>
   * The path of attributes.
   * The attribute path for a TableAttrDef is `(input|output)/(IoDef
   * name)/(TableAttrDef name)(/(column name)(/(extra attributes))?)?`.
   * </pre>
   *
   * <code>repeated string attr_paths = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the attrPaths at the given index.
   */
  public com.google.protobuf.ByteString
      getAttrPathsBytes(int index) {
    return attrPaths_.getByteString(index);
  }

  public static final int ATTRS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.secretflow.spec.v1.Attribute> attrs_;
  /**
   * <pre>
   * The value of the attribute.
   * Must match attr_paths.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.secretflow.spec.v1.Attribute> getAttrsList() {
    return attrs_;
  }
  /**
   * <pre>
   * The value of the attribute.
   * Must match attr_paths.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.secretflow.spec.v1.AttributeOrBuilder> 
      getAttrsOrBuilderList() {
    return attrs_;
  }
  /**
   * <pre>
   * The value of the attribute.
   * Must match attr_paths.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
   */
  @java.lang.Override
  public int getAttrsCount() {
    return attrs_.size();
  }
  /**
   * <pre>
   * The value of the attribute.
   * Must match attr_paths.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.Attribute getAttrs(int index) {
    return attrs_.get(index);
  }
  /**
   * <pre>
   * The value of the attribute.
   * Must match attr_paths.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.AttributeOrBuilder getAttrsOrBuilder(
      int index) {
    return attrs_.get(index);
  }

  public static final int INPUTS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<com.secretflow.spec.v1.DistData> inputs_;
  /**
   * <pre>
   * The input data, the order of inputs must match inputs in ComponentDef.
   * NOTE: Names of DistData doesn't need to match those of inputs in
   * ComponentDef definition.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
   */
  @java.lang.Override
  public java.util.List<com.secretflow.spec.v1.DistData> getInputsList() {
    return inputs_;
  }
  /**
   * <pre>
   * The input data, the order of inputs must match inputs in ComponentDef.
   * NOTE: Names of DistData doesn't need to match those of inputs in
   * ComponentDef definition.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.secretflow.spec.v1.DistDataOrBuilder> 
      getInputsOrBuilderList() {
    return inputs_;
  }
  /**
   * <pre>
   * The input data, the order of inputs must match inputs in ComponentDef.
   * NOTE: Names of DistData doesn't need to match those of inputs in
   * ComponentDef definition.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
   */
  @java.lang.Override
  public int getInputsCount() {
    return inputs_.size();
  }
  /**
   * <pre>
   * The input data, the order of inputs must match inputs in ComponentDef.
   * NOTE: Names of DistData doesn't need to match those of inputs in
   * ComponentDef definition.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.DistData getInputs(int index) {
    return inputs_.get(index);
  }
  /**
   * <pre>
   * The input data, the order of inputs must match inputs in ComponentDef.
   * NOTE: Names of DistData doesn't need to match those of inputs in
   * ComponentDef definition.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.DistDataOrBuilder getInputsOrBuilder(
      int index) {
    return inputs_.get(index);
  }

  public static final int OUTPUT_URIS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList outputUris_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * The output data uris, the order of output_uris must match outputs in
   * ComponentDef.
   * </pre>
   *
   * <code>repeated string output_uris = 7;</code>
   * @return A list containing the outputUris.
   */
  public com.google.protobuf.ProtocolStringList
      getOutputUrisList() {
    return outputUris_;
  }
  /**
   * <pre>
   * The output data uris, the order of output_uris must match outputs in
   * ComponentDef.
   * </pre>
   *
   * <code>repeated string output_uris = 7;</code>
   * @return The count of outputUris.
   */
  public int getOutputUrisCount() {
    return outputUris_.size();
  }
  /**
   * <pre>
   * The output data uris, the order of output_uris must match outputs in
   * ComponentDef.
   * </pre>
   *
   * <code>repeated string output_uris = 7;</code>
   * @param index The index of the element to return.
   * @return The outputUris at the given index.
   */
  public java.lang.String getOutputUris(int index) {
    return outputUris_.get(index);
  }
  /**
   * <pre>
   * The output data uris, the order of output_uris must match outputs in
   * ComponentDef.
   * </pre>
   *
   * <code>repeated string output_uris = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the outputUris at the given index.
   */
  public com.google.protobuf.ByteString
      getOutputUrisBytes(int index) {
    return outputUris_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(domain_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, domain_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, version_);
    }
    for (int i = 0; i < attrPaths_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, attrPaths_.getRaw(i));
    }
    for (int i = 0; i < attrs_.size(); i++) {
      output.writeMessage(5, attrs_.get(i));
    }
    for (int i = 0; i < inputs_.size(); i++) {
      output.writeMessage(6, inputs_.get(i));
    }
    for (int i = 0; i < outputUris_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, outputUris_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(domain_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, domain_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, version_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < attrPaths_.size(); i++) {
        dataSize += computeStringSizeNoTag(attrPaths_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAttrPathsList().size();
    }
    for (int i = 0; i < attrs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, attrs_.get(i));
    }
    for (int i = 0; i < inputs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, inputs_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < outputUris_.size(); i++) {
        dataSize += computeStringSizeNoTag(outputUris_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOutputUrisList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.secretflow.spec.v1.NodeEvalParam)) {
      return super.equals(obj);
    }
    com.secretflow.spec.v1.NodeEvalParam other = (com.secretflow.spec.v1.NodeEvalParam) obj;

    if (!getDomain()
        .equals(other.getDomain())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (!getAttrPathsList()
        .equals(other.getAttrPathsList())) return false;
    if (!getAttrsList()
        .equals(other.getAttrsList())) return false;
    if (!getInputsList()
        .equals(other.getInputsList())) return false;
    if (!getOutputUrisList()
        .equals(other.getOutputUrisList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
    hash = (53 * hash) + getDomain().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    if (getAttrPathsCount() > 0) {
      hash = (37 * hash) + ATTR_PATHS_FIELD_NUMBER;
      hash = (53 * hash) + getAttrPathsList().hashCode();
    }
    if (getAttrsCount() > 0) {
      hash = (37 * hash) + ATTRS_FIELD_NUMBER;
      hash = (53 * hash) + getAttrsList().hashCode();
    }
    if (getInputsCount() > 0) {
      hash = (37 * hash) + INPUTS_FIELD_NUMBER;
      hash = (53 * hash) + getInputsList().hashCode();
    }
    if (getOutputUrisCount() > 0) {
      hash = (37 * hash) + OUTPUT_URIS_FIELD_NUMBER;
      hash = (53 * hash) + getOutputUrisList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.secretflow.spec.v1.NodeEvalParam parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.NodeEvalParam parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.NodeEvalParam parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.NodeEvalParam parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.NodeEvalParam parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.NodeEvalParam parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.NodeEvalParam parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.NodeEvalParam parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.NodeEvalParam parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.NodeEvalParam parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.NodeEvalParam parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.NodeEvalParam parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.secretflow.spec.v1.NodeEvalParam prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Evaluate a node.
   * - CompListDef + StorageConfig + NodeEvalParam + other extra configs -&gt;
   * NodeEvalResult
   *
   * NodeEvalParam contains all the information to evaluate a component.
   * </pre>
   *
   * Protobuf type {@code secretflow.spec.v1.NodeEvalParam}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:secretflow.spec.v1.NodeEvalParam)
      com.secretflow.spec.v1.NodeEvalParamOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secretflow.spec.v1.EvaluationProto.internal_static_secretflow_spec_v1_NodeEvalParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secretflow.spec.v1.EvaluationProto.internal_static_secretflow_spec_v1_NodeEvalParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secretflow.spec.v1.NodeEvalParam.class, com.secretflow.spec.v1.NodeEvalParam.Builder.class);
    }

    // Construct using com.secretflow.spec.v1.NodeEvalParam.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      domain_ = "";
      name_ = "";
      version_ = "";
      attrPaths_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (attrsBuilder_ == null) {
        attrs_ = java.util.Collections.emptyList();
      } else {
        attrs_ = null;
        attrsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (inputsBuilder_ == null) {
        inputs_ = java.util.Collections.emptyList();
      } else {
        inputs_ = null;
        inputsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      outputUris_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.secretflow.spec.v1.EvaluationProto.internal_static_secretflow_spec_v1_NodeEvalParam_descriptor;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.NodeEvalParam getDefaultInstanceForType() {
      return com.secretflow.spec.v1.NodeEvalParam.getDefaultInstance();
    }

    @java.lang.Override
    public com.secretflow.spec.v1.NodeEvalParam build() {
      com.secretflow.spec.v1.NodeEvalParam result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.NodeEvalParam buildPartial() {
      com.secretflow.spec.v1.NodeEvalParam result = new com.secretflow.spec.v1.NodeEvalParam(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.secretflow.spec.v1.NodeEvalParam result) {
      if (attrsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          attrs_ = java.util.Collections.unmodifiableList(attrs_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.attrs_ = attrs_;
      } else {
        result.attrs_ = attrsBuilder_.build();
      }
      if (inputsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          inputs_ = java.util.Collections.unmodifiableList(inputs_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.inputs_ = inputs_;
      } else {
        result.inputs_ = inputsBuilder_.build();
      }
    }

    private void buildPartial0(com.secretflow.spec.v1.NodeEvalParam result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.domain_ = domain_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        attrPaths_.makeImmutable();
        result.attrPaths_ = attrPaths_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        outputUris_.makeImmutable();
        result.outputUris_ = outputUris_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.secretflow.spec.v1.NodeEvalParam) {
        return mergeFrom((com.secretflow.spec.v1.NodeEvalParam)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.secretflow.spec.v1.NodeEvalParam other) {
      if (other == com.secretflow.spec.v1.NodeEvalParam.getDefaultInstance()) return this;
      if (!other.getDomain().isEmpty()) {
        domain_ = other.domain_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.attrPaths_.isEmpty()) {
        if (attrPaths_.isEmpty()) {
          attrPaths_ = other.attrPaths_;
          bitField0_ |= 0x00000008;
        } else {
          ensureAttrPathsIsMutable();
          attrPaths_.addAll(other.attrPaths_);
        }
        onChanged();
      }
      if (attrsBuilder_ == null) {
        if (!other.attrs_.isEmpty()) {
          if (attrs_.isEmpty()) {
            attrs_ = other.attrs_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureAttrsIsMutable();
            attrs_.addAll(other.attrs_);
          }
          onChanged();
        }
      } else {
        if (!other.attrs_.isEmpty()) {
          if (attrsBuilder_.isEmpty()) {
            attrsBuilder_.dispose();
            attrsBuilder_ = null;
            attrs_ = other.attrs_;
            bitField0_ = (bitField0_ & ~0x00000010);
            attrsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAttrsFieldBuilder() : null;
          } else {
            attrsBuilder_.addAllMessages(other.attrs_);
          }
        }
      }
      if (inputsBuilder_ == null) {
        if (!other.inputs_.isEmpty()) {
          if (inputs_.isEmpty()) {
            inputs_ = other.inputs_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureInputsIsMutable();
            inputs_.addAll(other.inputs_);
          }
          onChanged();
        }
      } else {
        if (!other.inputs_.isEmpty()) {
          if (inputsBuilder_.isEmpty()) {
            inputsBuilder_.dispose();
            inputsBuilder_ = null;
            inputs_ = other.inputs_;
            bitField0_ = (bitField0_ & ~0x00000020);
            inputsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInputsFieldBuilder() : null;
          } else {
            inputsBuilder_.addAllMessages(other.inputs_);
          }
        }
      }
      if (!other.outputUris_.isEmpty()) {
        if (outputUris_.isEmpty()) {
          outputUris_ = other.outputUris_;
          bitField0_ |= 0x00000040;
        } else {
          ensureOutputUrisIsMutable();
          outputUris_.addAll(other.outputUris_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              domain_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              version_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureAttrPathsIsMutable();
              attrPaths_.add(s);
              break;
            } // case 34
            case 42: {
              com.secretflow.spec.v1.Attribute m =
                  input.readMessage(
                      com.secretflow.spec.v1.Attribute.parser(),
                      extensionRegistry);
              if (attrsBuilder_ == null) {
                ensureAttrsIsMutable();
                attrs_.add(m);
              } else {
                attrsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              com.secretflow.spec.v1.DistData m =
                  input.readMessage(
                      com.secretflow.spec.v1.DistData.parser(),
                      extensionRegistry);
              if (inputsBuilder_ == null) {
                ensureInputsIsMutable();
                inputs_.add(m);
              } else {
                inputsBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureOutputUrisIsMutable();
              outputUris_.add(s);
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object domain_ = "";
    /**
     * <pre>
     * Domain of the component.
     * </pre>
     *
     * <code>string domain = 1;</code>
     * @return The domain.
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Domain of the component.
     * </pre>
     *
     * <code>string domain = 1;</code>
     * @return The bytes for domain.
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Domain of the component.
     * </pre>
     *
     * <code>string domain = 1;</code>
     * @param value The domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomain(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      domain_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Domain of the component.
     * </pre>
     *
     * <code>string domain = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDomain() {
      domain_ = getDefaultInstance().getDomain();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Domain of the component.
     * </pre>
     *
     * <code>string domain = 1;</code>
     * @param value The bytes for domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      domain_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Name of the component.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the component.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the component.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the component.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the component.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <pre>
     * Version of the component.
     * </pre>
     *
     * <code>string version = 3;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Version of the component.
     * </pre>
     *
     * <code>string version = 3;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Version of the component.
     * </pre>
     *
     * <code>string version = 3;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      version_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of the component.
     * </pre>
     *
     * <code>string version = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      version_ = getDefaultInstance().getVersion();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of the component.
     * </pre>
     *
     * <code>string version = 3;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      version_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList attrPaths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureAttrPathsIsMutable() {
      if (!attrPaths_.isModifiable()) {
        attrPaths_ = new com.google.protobuf.LazyStringArrayList(attrPaths_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <pre>
     * The path of attributes.
     * The attribute path for a TableAttrDef is `(input|output)/(IoDef
     * name)/(TableAttrDef name)(/(column name)(/(extra attributes))?)?`.
     * </pre>
     *
     * <code>repeated string attr_paths = 4;</code>
     * @return A list containing the attrPaths.
     */
    public com.google.protobuf.ProtocolStringList
        getAttrPathsList() {
      attrPaths_.makeImmutable();
      return attrPaths_;
    }
    /**
     * <pre>
     * The path of attributes.
     * The attribute path for a TableAttrDef is `(input|output)/(IoDef
     * name)/(TableAttrDef name)(/(column name)(/(extra attributes))?)?`.
     * </pre>
     *
     * <code>repeated string attr_paths = 4;</code>
     * @return The count of attrPaths.
     */
    public int getAttrPathsCount() {
      return attrPaths_.size();
    }
    /**
     * <pre>
     * The path of attributes.
     * The attribute path for a TableAttrDef is `(input|output)/(IoDef
     * name)/(TableAttrDef name)(/(column name)(/(extra attributes))?)?`.
     * </pre>
     *
     * <code>repeated string attr_paths = 4;</code>
     * @param index The index of the element to return.
     * @return The attrPaths at the given index.
     */
    public java.lang.String getAttrPaths(int index) {
      return attrPaths_.get(index);
    }
    /**
     * <pre>
     * The path of attributes.
     * The attribute path for a TableAttrDef is `(input|output)/(IoDef
     * name)/(TableAttrDef name)(/(column name)(/(extra attributes))?)?`.
     * </pre>
     *
     * <code>repeated string attr_paths = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the attrPaths at the given index.
     */
    public com.google.protobuf.ByteString
        getAttrPathsBytes(int index) {
      return attrPaths_.getByteString(index);
    }
    /**
     * <pre>
     * The path of attributes.
     * The attribute path for a TableAttrDef is `(input|output)/(IoDef
     * name)/(TableAttrDef name)(/(column name)(/(extra attributes))?)?`.
     * </pre>
     *
     * <code>repeated string attr_paths = 4;</code>
     * @param index The index to set the value at.
     * @param value The attrPaths to set.
     * @return This builder for chaining.
     */
    public Builder setAttrPaths(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAttrPathsIsMutable();
      attrPaths_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The path of attributes.
     * The attribute path for a TableAttrDef is `(input|output)/(IoDef
     * name)/(TableAttrDef name)(/(column name)(/(extra attributes))?)?`.
     * </pre>
     *
     * <code>repeated string attr_paths = 4;</code>
     * @param value The attrPaths to add.
     * @return This builder for chaining.
     */
    public Builder addAttrPaths(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAttrPathsIsMutable();
      attrPaths_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The path of attributes.
     * The attribute path for a TableAttrDef is `(input|output)/(IoDef
     * name)/(TableAttrDef name)(/(column name)(/(extra attributes))?)?`.
     * </pre>
     *
     * <code>repeated string attr_paths = 4;</code>
     * @param values The attrPaths to add.
     * @return This builder for chaining.
     */
    public Builder addAllAttrPaths(
        java.lang.Iterable<java.lang.String> values) {
      ensureAttrPathsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, attrPaths_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The path of attributes.
     * The attribute path for a TableAttrDef is `(input|output)/(IoDef
     * name)/(TableAttrDef name)(/(column name)(/(extra attributes))?)?`.
     * </pre>
     *
     * <code>repeated string attr_paths = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttrPaths() {
      attrPaths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The path of attributes.
     * The attribute path for a TableAttrDef is `(input|output)/(IoDef
     * name)/(TableAttrDef name)(/(column name)(/(extra attributes))?)?`.
     * </pre>
     *
     * <code>repeated string attr_paths = 4;</code>
     * @param value The bytes of the attrPaths to add.
     * @return This builder for chaining.
     */
    public Builder addAttrPathsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureAttrPathsIsMutable();
      attrPaths_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.util.List<com.secretflow.spec.v1.Attribute> attrs_ =
      java.util.Collections.emptyList();
    private void ensureAttrsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        attrs_ = new java.util.ArrayList<com.secretflow.spec.v1.Attribute>(attrs_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.Attribute, com.secretflow.spec.v1.Attribute.Builder, com.secretflow.spec.v1.AttributeOrBuilder> attrsBuilder_;

    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public java.util.List<com.secretflow.spec.v1.Attribute> getAttrsList() {
      if (attrsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attrs_);
      } else {
        return attrsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public int getAttrsCount() {
      if (attrsBuilder_ == null) {
        return attrs_.size();
      } else {
        return attrsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public com.secretflow.spec.v1.Attribute getAttrs(int index) {
      if (attrsBuilder_ == null) {
        return attrs_.get(index);
      } else {
        return attrsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public Builder setAttrs(
        int index, com.secretflow.spec.v1.Attribute value) {
      if (attrsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttrsIsMutable();
        attrs_.set(index, value);
        onChanged();
      } else {
        attrsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public Builder setAttrs(
        int index, com.secretflow.spec.v1.Attribute.Builder builderForValue) {
      if (attrsBuilder_ == null) {
        ensureAttrsIsMutable();
        attrs_.set(index, builderForValue.build());
        onChanged();
      } else {
        attrsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public Builder addAttrs(com.secretflow.spec.v1.Attribute value) {
      if (attrsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttrsIsMutable();
        attrs_.add(value);
        onChanged();
      } else {
        attrsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public Builder addAttrs(
        int index, com.secretflow.spec.v1.Attribute value) {
      if (attrsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttrsIsMutable();
        attrs_.add(index, value);
        onChanged();
      } else {
        attrsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public Builder addAttrs(
        com.secretflow.spec.v1.Attribute.Builder builderForValue) {
      if (attrsBuilder_ == null) {
        ensureAttrsIsMutable();
        attrs_.add(builderForValue.build());
        onChanged();
      } else {
        attrsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public Builder addAttrs(
        int index, com.secretflow.spec.v1.Attribute.Builder builderForValue) {
      if (attrsBuilder_ == null) {
        ensureAttrsIsMutable();
        attrs_.add(index, builderForValue.build());
        onChanged();
      } else {
        attrsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public Builder addAllAttrs(
        java.lang.Iterable<? extends com.secretflow.spec.v1.Attribute> values) {
      if (attrsBuilder_ == null) {
        ensureAttrsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attrs_);
        onChanged();
      } else {
        attrsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public Builder clearAttrs() {
      if (attrsBuilder_ == null) {
        attrs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        attrsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public Builder removeAttrs(int index) {
      if (attrsBuilder_ == null) {
        ensureAttrsIsMutable();
        attrs_.remove(index);
        onChanged();
      } else {
        attrsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public com.secretflow.spec.v1.Attribute.Builder getAttrsBuilder(
        int index) {
      return getAttrsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public com.secretflow.spec.v1.AttributeOrBuilder getAttrsOrBuilder(
        int index) {
      if (attrsBuilder_ == null) {
        return attrs_.get(index);  } else {
        return attrsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public java.util.List<? extends com.secretflow.spec.v1.AttributeOrBuilder> 
         getAttrsOrBuilderList() {
      if (attrsBuilder_ != null) {
        return attrsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attrs_);
      }
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public com.secretflow.spec.v1.Attribute.Builder addAttrsBuilder() {
      return getAttrsFieldBuilder().addBuilder(
          com.secretflow.spec.v1.Attribute.getDefaultInstance());
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public com.secretflow.spec.v1.Attribute.Builder addAttrsBuilder(
        int index) {
      return getAttrsFieldBuilder().addBuilder(
          index, com.secretflow.spec.v1.Attribute.getDefaultInstance());
    }
    /**
     * <pre>
     * The value of the attribute.
     * Must match attr_paths.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.Attribute attrs = 5;</code>
     */
    public java.util.List<com.secretflow.spec.v1.Attribute.Builder> 
         getAttrsBuilderList() {
      return getAttrsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.Attribute, com.secretflow.spec.v1.Attribute.Builder, com.secretflow.spec.v1.AttributeOrBuilder> 
        getAttrsFieldBuilder() {
      if (attrsBuilder_ == null) {
        attrsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.secretflow.spec.v1.Attribute, com.secretflow.spec.v1.Attribute.Builder, com.secretflow.spec.v1.AttributeOrBuilder>(
                attrs_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        attrs_ = null;
      }
      return attrsBuilder_;
    }

    private java.util.List<com.secretflow.spec.v1.DistData> inputs_ =
      java.util.Collections.emptyList();
    private void ensureInputsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        inputs_ = new java.util.ArrayList<com.secretflow.spec.v1.DistData>(inputs_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.DistData, com.secretflow.spec.v1.DistData.Builder, com.secretflow.spec.v1.DistDataOrBuilder> inputsBuilder_;

    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public java.util.List<com.secretflow.spec.v1.DistData> getInputsList() {
      if (inputsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(inputs_);
      } else {
        return inputsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public int getInputsCount() {
      if (inputsBuilder_ == null) {
        return inputs_.size();
      } else {
        return inputsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public com.secretflow.spec.v1.DistData getInputs(int index) {
      if (inputsBuilder_ == null) {
        return inputs_.get(index);
      } else {
        return inputsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public Builder setInputs(
        int index, com.secretflow.spec.v1.DistData value) {
      if (inputsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInputsIsMutable();
        inputs_.set(index, value);
        onChanged();
      } else {
        inputsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public Builder setInputs(
        int index, com.secretflow.spec.v1.DistData.Builder builderForValue) {
      if (inputsBuilder_ == null) {
        ensureInputsIsMutable();
        inputs_.set(index, builderForValue.build());
        onChanged();
      } else {
        inputsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public Builder addInputs(com.secretflow.spec.v1.DistData value) {
      if (inputsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInputsIsMutable();
        inputs_.add(value);
        onChanged();
      } else {
        inputsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public Builder addInputs(
        int index, com.secretflow.spec.v1.DistData value) {
      if (inputsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInputsIsMutable();
        inputs_.add(index, value);
        onChanged();
      } else {
        inputsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public Builder addInputs(
        com.secretflow.spec.v1.DistData.Builder builderForValue) {
      if (inputsBuilder_ == null) {
        ensureInputsIsMutable();
        inputs_.add(builderForValue.build());
        onChanged();
      } else {
        inputsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public Builder addInputs(
        int index, com.secretflow.spec.v1.DistData.Builder builderForValue) {
      if (inputsBuilder_ == null) {
        ensureInputsIsMutable();
        inputs_.add(index, builderForValue.build());
        onChanged();
      } else {
        inputsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public Builder addAllInputs(
        java.lang.Iterable<? extends com.secretflow.spec.v1.DistData> values) {
      if (inputsBuilder_ == null) {
        ensureInputsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, inputs_);
        onChanged();
      } else {
        inputsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public Builder clearInputs() {
      if (inputsBuilder_ == null) {
        inputs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        inputsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public Builder removeInputs(int index) {
      if (inputsBuilder_ == null) {
        ensureInputsIsMutable();
        inputs_.remove(index);
        onChanged();
      } else {
        inputsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public com.secretflow.spec.v1.DistData.Builder getInputsBuilder(
        int index) {
      return getInputsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public com.secretflow.spec.v1.DistDataOrBuilder getInputsOrBuilder(
        int index) {
      if (inputsBuilder_ == null) {
        return inputs_.get(index);  } else {
        return inputsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public java.util.List<? extends com.secretflow.spec.v1.DistDataOrBuilder> 
         getInputsOrBuilderList() {
      if (inputsBuilder_ != null) {
        return inputsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(inputs_);
      }
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public com.secretflow.spec.v1.DistData.Builder addInputsBuilder() {
      return getInputsFieldBuilder().addBuilder(
          com.secretflow.spec.v1.DistData.getDefaultInstance());
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public com.secretflow.spec.v1.DistData.Builder addInputsBuilder(
        int index) {
      return getInputsFieldBuilder().addBuilder(
          index, com.secretflow.spec.v1.DistData.getDefaultInstance());
    }
    /**
     * <pre>
     * The input data, the order of inputs must match inputs in ComponentDef.
     * NOTE: Names of DistData doesn't need to match those of inputs in
     * ComponentDef definition.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData inputs = 6;</code>
     */
    public java.util.List<com.secretflow.spec.v1.DistData.Builder> 
         getInputsBuilderList() {
      return getInputsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.DistData, com.secretflow.spec.v1.DistData.Builder, com.secretflow.spec.v1.DistDataOrBuilder> 
        getInputsFieldBuilder() {
      if (inputsBuilder_ == null) {
        inputsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.secretflow.spec.v1.DistData, com.secretflow.spec.v1.DistData.Builder, com.secretflow.spec.v1.DistDataOrBuilder>(
                inputs_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        inputs_ = null;
      }
      return inputsBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList outputUris_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureOutputUrisIsMutable() {
      if (!outputUris_.isModifiable()) {
        outputUris_ = new com.google.protobuf.LazyStringArrayList(outputUris_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <pre>
     * The output data uris, the order of output_uris must match outputs in
     * ComponentDef.
     * </pre>
     *
     * <code>repeated string output_uris = 7;</code>
     * @return A list containing the outputUris.
     */
    public com.google.protobuf.ProtocolStringList
        getOutputUrisList() {
      outputUris_.makeImmutable();
      return outputUris_;
    }
    /**
     * <pre>
     * The output data uris, the order of output_uris must match outputs in
     * ComponentDef.
     * </pre>
     *
     * <code>repeated string output_uris = 7;</code>
     * @return The count of outputUris.
     */
    public int getOutputUrisCount() {
      return outputUris_.size();
    }
    /**
     * <pre>
     * The output data uris, the order of output_uris must match outputs in
     * ComponentDef.
     * </pre>
     *
     * <code>repeated string output_uris = 7;</code>
     * @param index The index of the element to return.
     * @return The outputUris at the given index.
     */
    public java.lang.String getOutputUris(int index) {
      return outputUris_.get(index);
    }
    /**
     * <pre>
     * The output data uris, the order of output_uris must match outputs in
     * ComponentDef.
     * </pre>
     *
     * <code>repeated string output_uris = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the outputUris at the given index.
     */
    public com.google.protobuf.ByteString
        getOutputUrisBytes(int index) {
      return outputUris_.getByteString(index);
    }
    /**
     * <pre>
     * The output data uris, the order of output_uris must match outputs in
     * ComponentDef.
     * </pre>
     *
     * <code>repeated string output_uris = 7;</code>
     * @param index The index to set the value at.
     * @param value The outputUris to set.
     * @return This builder for chaining.
     */
    public Builder setOutputUris(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOutputUrisIsMutable();
      outputUris_.set(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The output data uris, the order of output_uris must match outputs in
     * ComponentDef.
     * </pre>
     *
     * <code>repeated string output_uris = 7;</code>
     * @param value The outputUris to add.
     * @return This builder for chaining.
     */
    public Builder addOutputUris(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOutputUrisIsMutable();
      outputUris_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The output data uris, the order of output_uris must match outputs in
     * ComponentDef.
     * </pre>
     *
     * <code>repeated string output_uris = 7;</code>
     * @param values The outputUris to add.
     * @return This builder for chaining.
     */
    public Builder addAllOutputUris(
        java.lang.Iterable<java.lang.String> values) {
      ensureOutputUrisIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, outputUris_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The output data uris, the order of output_uris must match outputs in
     * ComponentDef.
     * </pre>
     *
     * <code>repeated string output_uris = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputUris() {
      outputUris_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The output data uris, the order of output_uris must match outputs in
     * ComponentDef.
     * </pre>
     *
     * <code>repeated string output_uris = 7;</code>
     * @param value The bytes of the outputUris to add.
     * @return This builder for chaining.
     */
    public Builder addOutputUrisBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureOutputUrisIsMutable();
      outputUris_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:secretflow.spec.v1.NodeEvalParam)
  }

  // @@protoc_insertion_point(class_scope:secretflow.spec.v1.NodeEvalParam)
  private static final com.secretflow.spec.v1.NodeEvalParam DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.secretflow.spec.v1.NodeEvalParam();
  }

  public static com.secretflow.spec.v1.NodeEvalParam getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NodeEvalParam>
      PARSER = new com.google.protobuf.AbstractParser<NodeEvalParam>() {
    @java.lang.Override
    public NodeEvalParam parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NodeEvalParam> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NodeEvalParam> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.secretflow.spec.v1.NodeEvalParam getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

