// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/spec/v1/evaluation.proto

package com.secretflow.spec.v1;

public interface NodeEvalResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:secretflow.spec.v1.NodeEvalResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Output data.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
   */
  java.util.List<com.secretflow.spec.v1.DistData> 
      getOutputsList();
  /**
   * <pre>
   * Output data.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
   */
  com.secretflow.spec.v1.DistData getOutputs(int index);
  /**
   * <pre>
   * Output data.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
   */
  int getOutputsCount();
  /**
   * <pre>
   * Output data.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
   */
  java.util.List<? extends com.secretflow.spec.v1.DistDataOrBuilder> 
      getOutputsOrBuilderList();
  /**
   * <pre>
   * Output data.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
   */
  com.secretflow.spec.v1.DistDataOrBuilder getOutputsOrBuilder(
      int index);
}
