// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/spec/v1/evaluation.proto

package com.secretflow.spec.v1;

/**
 * <pre>
 * NodeEvalResult contains outputs of a component evaluation.
 * </pre>
 *
 * Protobuf type {@code secretflow.spec.v1.NodeEvalResult}
 */
public final class NodeEvalResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:secretflow.spec.v1.NodeEvalResult)
    NodeEvalResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NodeEvalResult.newBuilder() to construct.
  private NodeEvalResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NodeEvalResult() {
    outputs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NodeEvalResult();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.secretflow.spec.v1.EvaluationProto.internal_static_secretflow_spec_v1_NodeEvalResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.secretflow.spec.v1.EvaluationProto.internal_static_secretflow_spec_v1_NodeEvalResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.secretflow.spec.v1.NodeEvalResult.class, com.secretflow.spec.v1.NodeEvalResult.Builder.class);
  }

  public static final int OUTPUTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.secretflow.spec.v1.DistData> outputs_;
  /**
   * <pre>
   * Output data.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.secretflow.spec.v1.DistData> getOutputsList() {
    return outputs_;
  }
  /**
   * <pre>
   * Output data.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.secretflow.spec.v1.DistDataOrBuilder> 
      getOutputsOrBuilderList() {
    return outputs_;
  }
  /**
   * <pre>
   * Output data.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
   */
  @java.lang.Override
  public int getOutputsCount() {
    return outputs_.size();
  }
  /**
   * <pre>
   * Output data.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.DistData getOutputs(int index) {
    return outputs_.get(index);
  }
  /**
   * <pre>
   * Output data.
   * </pre>
   *
   * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.DistDataOrBuilder getOutputsOrBuilder(
      int index) {
    return outputs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < outputs_.size(); i++) {
      output.writeMessage(1, outputs_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < outputs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, outputs_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.secretflow.spec.v1.NodeEvalResult)) {
      return super.equals(obj);
    }
    com.secretflow.spec.v1.NodeEvalResult other = (com.secretflow.spec.v1.NodeEvalResult) obj;

    if (!getOutputsList()
        .equals(other.getOutputsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOutputsCount() > 0) {
      hash = (37 * hash) + OUTPUTS_FIELD_NUMBER;
      hash = (53 * hash) + getOutputsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.secretflow.spec.v1.NodeEvalResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.NodeEvalResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.NodeEvalResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.NodeEvalResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.NodeEvalResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.NodeEvalResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.NodeEvalResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.NodeEvalResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.NodeEvalResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.NodeEvalResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.NodeEvalResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.NodeEvalResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.secretflow.spec.v1.NodeEvalResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * NodeEvalResult contains outputs of a component evaluation.
   * </pre>
   *
   * Protobuf type {@code secretflow.spec.v1.NodeEvalResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:secretflow.spec.v1.NodeEvalResult)
      com.secretflow.spec.v1.NodeEvalResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secretflow.spec.v1.EvaluationProto.internal_static_secretflow_spec_v1_NodeEvalResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secretflow.spec.v1.EvaluationProto.internal_static_secretflow_spec_v1_NodeEvalResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secretflow.spec.v1.NodeEvalResult.class, com.secretflow.spec.v1.NodeEvalResult.Builder.class);
    }

    // Construct using com.secretflow.spec.v1.NodeEvalResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (outputsBuilder_ == null) {
        outputs_ = java.util.Collections.emptyList();
      } else {
        outputs_ = null;
        outputsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.secretflow.spec.v1.EvaluationProto.internal_static_secretflow_spec_v1_NodeEvalResult_descriptor;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.NodeEvalResult getDefaultInstanceForType() {
      return com.secretflow.spec.v1.NodeEvalResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.secretflow.spec.v1.NodeEvalResult build() {
      com.secretflow.spec.v1.NodeEvalResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.NodeEvalResult buildPartial() {
      com.secretflow.spec.v1.NodeEvalResult result = new com.secretflow.spec.v1.NodeEvalResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.secretflow.spec.v1.NodeEvalResult result) {
      if (outputsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          outputs_ = java.util.Collections.unmodifiableList(outputs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.outputs_ = outputs_;
      } else {
        result.outputs_ = outputsBuilder_.build();
      }
    }

    private void buildPartial0(com.secretflow.spec.v1.NodeEvalResult result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.secretflow.spec.v1.NodeEvalResult) {
        return mergeFrom((com.secretflow.spec.v1.NodeEvalResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.secretflow.spec.v1.NodeEvalResult other) {
      if (other == com.secretflow.spec.v1.NodeEvalResult.getDefaultInstance()) return this;
      if (outputsBuilder_ == null) {
        if (!other.outputs_.isEmpty()) {
          if (outputs_.isEmpty()) {
            outputs_ = other.outputs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOutputsIsMutable();
            outputs_.addAll(other.outputs_);
          }
          onChanged();
        }
      } else {
        if (!other.outputs_.isEmpty()) {
          if (outputsBuilder_.isEmpty()) {
            outputsBuilder_.dispose();
            outputsBuilder_ = null;
            outputs_ = other.outputs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            outputsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOutputsFieldBuilder() : null;
          } else {
            outputsBuilder_.addAllMessages(other.outputs_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.secretflow.spec.v1.DistData m =
                  input.readMessage(
                      com.secretflow.spec.v1.DistData.parser(),
                      extensionRegistry);
              if (outputsBuilder_ == null) {
                ensureOutputsIsMutable();
                outputs_.add(m);
              } else {
                outputsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.secretflow.spec.v1.DistData> outputs_ =
      java.util.Collections.emptyList();
    private void ensureOutputsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        outputs_ = new java.util.ArrayList<com.secretflow.spec.v1.DistData>(outputs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.DistData, com.secretflow.spec.v1.DistData.Builder, com.secretflow.spec.v1.DistDataOrBuilder> outputsBuilder_;

    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public java.util.List<com.secretflow.spec.v1.DistData> getOutputsList() {
      if (outputsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(outputs_);
      } else {
        return outputsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public int getOutputsCount() {
      if (outputsBuilder_ == null) {
        return outputs_.size();
      } else {
        return outputsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public com.secretflow.spec.v1.DistData getOutputs(int index) {
      if (outputsBuilder_ == null) {
        return outputs_.get(index);
      } else {
        return outputsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public Builder setOutputs(
        int index, com.secretflow.spec.v1.DistData value) {
      if (outputsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutputsIsMutable();
        outputs_.set(index, value);
        onChanged();
      } else {
        outputsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public Builder setOutputs(
        int index, com.secretflow.spec.v1.DistData.Builder builderForValue) {
      if (outputsBuilder_ == null) {
        ensureOutputsIsMutable();
        outputs_.set(index, builderForValue.build());
        onChanged();
      } else {
        outputsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public Builder addOutputs(com.secretflow.spec.v1.DistData value) {
      if (outputsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutputsIsMutable();
        outputs_.add(value);
        onChanged();
      } else {
        outputsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public Builder addOutputs(
        int index, com.secretflow.spec.v1.DistData value) {
      if (outputsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutputsIsMutable();
        outputs_.add(index, value);
        onChanged();
      } else {
        outputsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public Builder addOutputs(
        com.secretflow.spec.v1.DistData.Builder builderForValue) {
      if (outputsBuilder_ == null) {
        ensureOutputsIsMutable();
        outputs_.add(builderForValue.build());
        onChanged();
      } else {
        outputsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public Builder addOutputs(
        int index, com.secretflow.spec.v1.DistData.Builder builderForValue) {
      if (outputsBuilder_ == null) {
        ensureOutputsIsMutable();
        outputs_.add(index, builderForValue.build());
        onChanged();
      } else {
        outputsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public Builder addAllOutputs(
        java.lang.Iterable<? extends com.secretflow.spec.v1.DistData> values) {
      if (outputsBuilder_ == null) {
        ensureOutputsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, outputs_);
        onChanged();
      } else {
        outputsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public Builder clearOutputs() {
      if (outputsBuilder_ == null) {
        outputs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        outputsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public Builder removeOutputs(int index) {
      if (outputsBuilder_ == null) {
        ensureOutputsIsMutable();
        outputs_.remove(index);
        onChanged();
      } else {
        outputsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public com.secretflow.spec.v1.DistData.Builder getOutputsBuilder(
        int index) {
      return getOutputsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public com.secretflow.spec.v1.DistDataOrBuilder getOutputsOrBuilder(
        int index) {
      if (outputsBuilder_ == null) {
        return outputs_.get(index);  } else {
        return outputsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public java.util.List<? extends com.secretflow.spec.v1.DistDataOrBuilder> 
         getOutputsOrBuilderList() {
      if (outputsBuilder_ != null) {
        return outputsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(outputs_);
      }
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public com.secretflow.spec.v1.DistData.Builder addOutputsBuilder() {
      return getOutputsFieldBuilder().addBuilder(
          com.secretflow.spec.v1.DistData.getDefaultInstance());
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public com.secretflow.spec.v1.DistData.Builder addOutputsBuilder(
        int index) {
      return getOutputsFieldBuilder().addBuilder(
          index, com.secretflow.spec.v1.DistData.getDefaultInstance());
    }
    /**
     * <pre>
     * Output data.
     * </pre>
     *
     * <code>repeated .secretflow.spec.v1.DistData outputs = 1;</code>
     */
    public java.util.List<com.secretflow.spec.v1.DistData.Builder> 
         getOutputsBuilderList() {
      return getOutputsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.DistData, com.secretflow.spec.v1.DistData.Builder, com.secretflow.spec.v1.DistDataOrBuilder> 
        getOutputsFieldBuilder() {
      if (outputsBuilder_ == null) {
        outputsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.secretflow.spec.v1.DistData, com.secretflow.spec.v1.DistData.Builder, com.secretflow.spec.v1.DistDataOrBuilder>(
                outputs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        outputs_ = null;
      }
      return outputsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:secretflow.spec.v1.NodeEvalResult)
  }

  // @@protoc_insertion_point(class_scope:secretflow.spec.v1.NodeEvalResult)
  private static final com.secretflow.spec.v1.NodeEvalResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.secretflow.spec.v1.NodeEvalResult();
  }

  public static com.secretflow.spec.v1.NodeEvalResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NodeEvalResult>
      PARSER = new com.google.protobuf.AbstractParser<NodeEvalResult>() {
    @java.lang.Override
    public NodeEvalResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NodeEvalResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NodeEvalResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.secretflow.spec.v1.NodeEvalResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

