// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/spec/v1/report.proto

package com.secretflow.spec.v1;

/**
 * Protobuf type {@code secretflow.spec.v1.Report}
 */
public final class Report extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:secretflow.spec.v1.Report)
    ReportOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Report.newBuilder() to construct.
  private Report(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Report() {
    name_ = "";
    desc_ = "";
    tabs_ = java.util.Collections.emptyList();
    errDetail_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Report();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Report_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Report_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.secretflow.spec.v1.Report.class, com.secretflow.spec.v1.Report.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Name of the Report.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the Report.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESC_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object desc_ = "";
  /**
   * <code>string desc = 2;</code>
   * @return The desc.
   */
  @java.lang.Override
  public java.lang.String getDesc() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      desc_ = s;
      return s;
    }
  }
  /**
   * <code>string desc = 2;</code>
   * @return The bytes for desc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescBytes() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      desc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.secretflow.spec.v1.Tab> tabs_;
  /**
   * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.secretflow.spec.v1.Tab> getTabsList() {
    return tabs_;
  }
  /**
   * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.secretflow.spec.v1.TabOrBuilder> 
      getTabsOrBuilderList() {
    return tabs_;
  }
  /**
   * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
   */
  @java.lang.Override
  public int getTabsCount() {
    return tabs_.size();
  }
  /**
   * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.Tab getTabs(int index) {
    return tabs_.get(index);
  }
  /**
   * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.TabOrBuilder getTabsOrBuilder(
      int index) {
    return tabs_.get(index);
  }

  public static final int ERR_CODE_FIELD_NUMBER = 4;
  private int errCode_ = 0;
  /**
   * <code>int32 err_code = 4;</code>
   * @return The errCode.
   */
  @java.lang.Override
  public int getErrCode() {
    return errCode_;
  }

  public static final int ERR_DETAIL_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errDetail_ = "";
  /**
   * <pre>
   * Structed error detail (JSON encoded message).
   * </pre>
   *
   * <code>string err_detail = 5;</code>
   * @return The errDetail.
   */
  @java.lang.Override
  public java.lang.String getErrDetail() {
    java.lang.Object ref = errDetail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errDetail_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Structed error detail (JSON encoded message).
   * </pre>
   *
   * <code>string err_detail = 5;</code>
   * @return The bytes for errDetail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrDetailBytes() {
    java.lang.Object ref = errDetail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errDetail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(desc_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
    }
    for (int i = 0; i < tabs_.size(); i++) {
      output.writeMessage(3, tabs_.get(i));
    }
    if (errCode_ != 0) {
      output.writeInt32(4, errCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errDetail_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, errDetail_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(desc_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
    }
    for (int i = 0; i < tabs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, tabs_.get(i));
    }
    if (errCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, errCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errDetail_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, errDetail_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.secretflow.spec.v1.Report)) {
      return super.equals(obj);
    }
    com.secretflow.spec.v1.Report other = (com.secretflow.spec.v1.Report) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getDesc()
        .equals(other.getDesc())) return false;
    if (!getTabsList()
        .equals(other.getTabsList())) return false;
    if (getErrCode()
        != other.getErrCode()) return false;
    if (!getErrDetail()
        .equals(other.getErrDetail())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESC_FIELD_NUMBER;
    hash = (53 * hash) + getDesc().hashCode();
    if (getTabsCount() > 0) {
      hash = (37 * hash) + TABS_FIELD_NUMBER;
      hash = (53 * hash) + getTabsList().hashCode();
    }
    hash = (37 * hash) + ERR_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getErrCode();
    hash = (37 * hash) + ERR_DETAIL_FIELD_NUMBER;
    hash = (53 * hash) + getErrDetail().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.secretflow.spec.v1.Report parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.Report parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Report parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.Report parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Report parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.Report parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Report parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.Report parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Report parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.Report parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Report parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.Report parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.secretflow.spec.v1.Report prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code secretflow.spec.v1.Report}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:secretflow.spec.v1.Report)
      com.secretflow.spec.v1.ReportOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Report_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Report_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secretflow.spec.v1.Report.class, com.secretflow.spec.v1.Report.Builder.class);
    }

    // Construct using com.secretflow.spec.v1.Report.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      desc_ = "";
      if (tabsBuilder_ == null) {
        tabs_ = java.util.Collections.emptyList();
      } else {
        tabs_ = null;
        tabsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      errCode_ = 0;
      errDetail_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Report_descriptor;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.Report getDefaultInstanceForType() {
      return com.secretflow.spec.v1.Report.getDefaultInstance();
    }

    @java.lang.Override
    public com.secretflow.spec.v1.Report build() {
      com.secretflow.spec.v1.Report result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.Report buildPartial() {
      com.secretflow.spec.v1.Report result = new com.secretflow.spec.v1.Report(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.secretflow.spec.v1.Report result) {
      if (tabsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          tabs_ = java.util.Collections.unmodifiableList(tabs_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.tabs_ = tabs_;
      } else {
        result.tabs_ = tabsBuilder_.build();
      }
    }

    private void buildPartial0(com.secretflow.spec.v1.Report result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.desc_ = desc_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.errCode_ = errCode_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.errDetail_ = errDetail_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.secretflow.spec.v1.Report) {
        return mergeFrom((com.secretflow.spec.v1.Report)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.secretflow.spec.v1.Report other) {
      if (other == com.secretflow.spec.v1.Report.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDesc().isEmpty()) {
        desc_ = other.desc_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (tabsBuilder_ == null) {
        if (!other.tabs_.isEmpty()) {
          if (tabs_.isEmpty()) {
            tabs_ = other.tabs_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTabsIsMutable();
            tabs_.addAll(other.tabs_);
          }
          onChanged();
        }
      } else {
        if (!other.tabs_.isEmpty()) {
          if (tabsBuilder_.isEmpty()) {
            tabsBuilder_.dispose();
            tabsBuilder_ = null;
            tabs_ = other.tabs_;
            bitField0_ = (bitField0_ & ~0x00000004);
            tabsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTabsFieldBuilder() : null;
          } else {
            tabsBuilder_.addAllMessages(other.tabs_);
          }
        }
      }
      if (other.getErrCode() != 0) {
        setErrCode(other.getErrCode());
      }
      if (!other.getErrDetail().isEmpty()) {
        errDetail_ = other.errDetail_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              desc_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.secretflow.spec.v1.Tab m =
                  input.readMessage(
                      com.secretflow.spec.v1.Tab.parser(),
                      extensionRegistry);
              if (tabsBuilder_ == null) {
                ensureTabsIsMutable();
                tabs_.add(m);
              } else {
                tabsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 32: {
              errCode_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              errDetail_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Name of the Report.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the Report.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the Report.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Report.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Report.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object desc_ = "";
    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string desc = 2;</code>
     * @param value The desc to set.
     * @return This builder for chaining.
     */
    public Builder setDesc(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      desc_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDesc() {
      desc_ = getDefaultInstance().getDesc();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 2;</code>
     * @param value The bytes for desc to set.
     * @return This builder for chaining.
     */
    public Builder setDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      desc_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<com.secretflow.spec.v1.Tab> tabs_ =
      java.util.Collections.emptyList();
    private void ensureTabsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        tabs_ = new java.util.ArrayList<com.secretflow.spec.v1.Tab>(tabs_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.Tab, com.secretflow.spec.v1.Tab.Builder, com.secretflow.spec.v1.TabOrBuilder> tabsBuilder_;

    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public java.util.List<com.secretflow.spec.v1.Tab> getTabsList() {
      if (tabsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tabs_);
      } else {
        return tabsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public int getTabsCount() {
      if (tabsBuilder_ == null) {
        return tabs_.size();
      } else {
        return tabsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public com.secretflow.spec.v1.Tab getTabs(int index) {
      if (tabsBuilder_ == null) {
        return tabs_.get(index);
      } else {
        return tabsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public Builder setTabs(
        int index, com.secretflow.spec.v1.Tab value) {
      if (tabsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTabsIsMutable();
        tabs_.set(index, value);
        onChanged();
      } else {
        tabsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public Builder setTabs(
        int index, com.secretflow.spec.v1.Tab.Builder builderForValue) {
      if (tabsBuilder_ == null) {
        ensureTabsIsMutable();
        tabs_.set(index, builderForValue.build());
        onChanged();
      } else {
        tabsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public Builder addTabs(com.secretflow.spec.v1.Tab value) {
      if (tabsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTabsIsMutable();
        tabs_.add(value);
        onChanged();
      } else {
        tabsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public Builder addTabs(
        int index, com.secretflow.spec.v1.Tab value) {
      if (tabsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTabsIsMutable();
        tabs_.add(index, value);
        onChanged();
      } else {
        tabsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public Builder addTabs(
        com.secretflow.spec.v1.Tab.Builder builderForValue) {
      if (tabsBuilder_ == null) {
        ensureTabsIsMutable();
        tabs_.add(builderForValue.build());
        onChanged();
      } else {
        tabsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public Builder addTabs(
        int index, com.secretflow.spec.v1.Tab.Builder builderForValue) {
      if (tabsBuilder_ == null) {
        ensureTabsIsMutable();
        tabs_.add(index, builderForValue.build());
        onChanged();
      } else {
        tabsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public Builder addAllTabs(
        java.lang.Iterable<? extends com.secretflow.spec.v1.Tab> values) {
      if (tabsBuilder_ == null) {
        ensureTabsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tabs_);
        onChanged();
      } else {
        tabsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public Builder clearTabs() {
      if (tabsBuilder_ == null) {
        tabs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        tabsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public Builder removeTabs(int index) {
      if (tabsBuilder_ == null) {
        ensureTabsIsMutable();
        tabs_.remove(index);
        onChanged();
      } else {
        tabsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public com.secretflow.spec.v1.Tab.Builder getTabsBuilder(
        int index) {
      return getTabsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public com.secretflow.spec.v1.TabOrBuilder getTabsOrBuilder(
        int index) {
      if (tabsBuilder_ == null) {
        return tabs_.get(index);  } else {
        return tabsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public java.util.List<? extends com.secretflow.spec.v1.TabOrBuilder> 
         getTabsOrBuilderList() {
      if (tabsBuilder_ != null) {
        return tabsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tabs_);
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public com.secretflow.spec.v1.Tab.Builder addTabsBuilder() {
      return getTabsFieldBuilder().addBuilder(
          com.secretflow.spec.v1.Tab.getDefaultInstance());
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public com.secretflow.spec.v1.Tab.Builder addTabsBuilder(
        int index) {
      return getTabsFieldBuilder().addBuilder(
          index, com.secretflow.spec.v1.Tab.getDefaultInstance());
    }
    /**
     * <code>repeated .secretflow.spec.v1.Tab tabs = 3;</code>
     */
    public java.util.List<com.secretflow.spec.v1.Tab.Builder> 
         getTabsBuilderList() {
      return getTabsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.Tab, com.secretflow.spec.v1.Tab.Builder, com.secretflow.spec.v1.TabOrBuilder> 
        getTabsFieldBuilder() {
      if (tabsBuilder_ == null) {
        tabsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.secretflow.spec.v1.Tab, com.secretflow.spec.v1.Tab.Builder, com.secretflow.spec.v1.TabOrBuilder>(
                tabs_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        tabs_ = null;
      }
      return tabsBuilder_;
    }

    private int errCode_ ;
    /**
     * <code>int32 err_code = 4;</code>
     * @return The errCode.
     */
    @java.lang.Override
    public int getErrCode() {
      return errCode_;
    }
    /**
     * <code>int32 err_code = 4;</code>
     * @param value The errCode to set.
     * @return This builder for chaining.
     */
    public Builder setErrCode(int value) {

      errCode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 err_code = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrCode() {
      bitField0_ = (bitField0_ & ~0x00000008);
      errCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errDetail_ = "";
    /**
     * <pre>
     * Structed error detail (JSON encoded message).
     * </pre>
     *
     * <code>string err_detail = 5;</code>
     * @return The errDetail.
     */
    public java.lang.String getErrDetail() {
      java.lang.Object ref = errDetail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errDetail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Structed error detail (JSON encoded message).
     * </pre>
     *
     * <code>string err_detail = 5;</code>
     * @return The bytes for errDetail.
     */
    public com.google.protobuf.ByteString
        getErrDetailBytes() {
      java.lang.Object ref = errDetail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errDetail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Structed error detail (JSON encoded message).
     * </pre>
     *
     * <code>string err_detail = 5;</code>
     * @param value The errDetail to set.
     * @return This builder for chaining.
     */
    public Builder setErrDetail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errDetail_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Structed error detail (JSON encoded message).
     * </pre>
     *
     * <code>string err_detail = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrDetail() {
      errDetail_ = getDefaultInstance().getErrDetail();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Structed error detail (JSON encoded message).
     * </pre>
     *
     * <code>string err_detail = 5;</code>
     * @param value The bytes for errDetail to set.
     * @return This builder for chaining.
     */
    public Builder setErrDetailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errDetail_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:secretflow.spec.v1.Report)
  }

  // @@protoc_insertion_point(class_scope:secretflow.spec.v1.Report)
  private static final com.secretflow.spec.v1.Report DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.secretflow.spec.v1.Report();
  }

  public static com.secretflow.spec.v1.Report getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Report>
      PARSER = new com.google.protobuf.AbstractParser<Report>() {
    @java.lang.Override
    public Report parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Report> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Report> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.secretflow.spec.v1.Report getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

