// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/spec/v1/report.proto

package com.secretflow.spec.v1;

/**
 * <pre>
 * A page of a report.
 * </pre>
 *
 * Protobuf type {@code secretflow.spec.v1.Tab}
 */
public final class Tab extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:secretflow.spec.v1.Tab)
    TabOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Tab.newBuilder() to construct.
  private Tab(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Tab() {
    name_ = "";
    desc_ = "";
    divs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Tab();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Tab_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Tab_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.secretflow.spec.v1.Tab.class, com.secretflow.spec.v1.Tab.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Name of the Tab.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the Tab.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESC_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object desc_ = "";
  /**
   * <code>string desc = 2;</code>
   * @return The desc.
   */
  @java.lang.Override
  public java.lang.String getDesc() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      desc_ = s;
      return s;
    }
  }
  /**
   * <code>string desc = 2;</code>
   * @return The bytes for desc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescBytes() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      desc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIVS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.secretflow.spec.v1.Div> divs_;
  /**
   * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.secretflow.spec.v1.Div> getDivsList() {
    return divs_;
  }
  /**
   * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.secretflow.spec.v1.DivOrBuilder> 
      getDivsOrBuilderList() {
    return divs_;
  }
  /**
   * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
   */
  @java.lang.Override
  public int getDivsCount() {
    return divs_.size();
  }
  /**
   * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.Div getDivs(int index) {
    return divs_.get(index);
  }
  /**
   * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
   */
  @java.lang.Override
  public com.secretflow.spec.v1.DivOrBuilder getDivsOrBuilder(
      int index) {
    return divs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(desc_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
    }
    for (int i = 0; i < divs_.size(); i++) {
      output.writeMessage(3, divs_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(desc_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
    }
    for (int i = 0; i < divs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, divs_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.secretflow.spec.v1.Tab)) {
      return super.equals(obj);
    }
    com.secretflow.spec.v1.Tab other = (com.secretflow.spec.v1.Tab) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getDesc()
        .equals(other.getDesc())) return false;
    if (!getDivsList()
        .equals(other.getDivsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESC_FIELD_NUMBER;
    hash = (53 * hash) + getDesc().hashCode();
    if (getDivsCount() > 0) {
      hash = (37 * hash) + DIVS_FIELD_NUMBER;
      hash = (53 * hash) + getDivsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.secretflow.spec.v1.Tab parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.Tab parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Tab parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.Tab parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Tab parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.secretflow.spec.v1.Tab parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Tab parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.Tab parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Tab parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.Tab parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.secretflow.spec.v1.Tab parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.secretflow.spec.v1.Tab parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.secretflow.spec.v1.Tab prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A page of a report.
   * </pre>
   *
   * Protobuf type {@code secretflow.spec.v1.Tab}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:secretflow.spec.v1.Tab)
      com.secretflow.spec.v1.TabOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Tab_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Tab_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secretflow.spec.v1.Tab.class, com.secretflow.spec.v1.Tab.Builder.class);
    }

    // Construct using com.secretflow.spec.v1.Tab.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      desc_ = "";
      if (divsBuilder_ == null) {
        divs_ = java.util.Collections.emptyList();
      } else {
        divs_ = null;
        divsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.secretflow.spec.v1.ReportProto.internal_static_secretflow_spec_v1_Tab_descriptor;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.Tab getDefaultInstanceForType() {
      return com.secretflow.spec.v1.Tab.getDefaultInstance();
    }

    @java.lang.Override
    public com.secretflow.spec.v1.Tab build() {
      com.secretflow.spec.v1.Tab result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.secretflow.spec.v1.Tab buildPartial() {
      com.secretflow.spec.v1.Tab result = new com.secretflow.spec.v1.Tab(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.secretflow.spec.v1.Tab result) {
      if (divsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          divs_ = java.util.Collections.unmodifiableList(divs_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.divs_ = divs_;
      } else {
        result.divs_ = divsBuilder_.build();
      }
    }

    private void buildPartial0(com.secretflow.spec.v1.Tab result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.desc_ = desc_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.secretflow.spec.v1.Tab) {
        return mergeFrom((com.secretflow.spec.v1.Tab)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.secretflow.spec.v1.Tab other) {
      if (other == com.secretflow.spec.v1.Tab.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDesc().isEmpty()) {
        desc_ = other.desc_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (divsBuilder_ == null) {
        if (!other.divs_.isEmpty()) {
          if (divs_.isEmpty()) {
            divs_ = other.divs_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDivsIsMutable();
            divs_.addAll(other.divs_);
          }
          onChanged();
        }
      } else {
        if (!other.divs_.isEmpty()) {
          if (divsBuilder_.isEmpty()) {
            divsBuilder_.dispose();
            divsBuilder_ = null;
            divs_ = other.divs_;
            bitField0_ = (bitField0_ & ~0x00000004);
            divsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDivsFieldBuilder() : null;
          } else {
            divsBuilder_.addAllMessages(other.divs_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              desc_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.secretflow.spec.v1.Div m =
                  input.readMessage(
                      com.secretflow.spec.v1.Div.parser(),
                      extensionRegistry);
              if (divsBuilder_ == null) {
                ensureDivsIsMutable();
                divs_.add(m);
              } else {
                divsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Name of the Tab.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the Tab.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the Tab.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Tab.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Tab.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object desc_ = "";
    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string desc = 2;</code>
     * @param value The desc to set.
     * @return This builder for chaining.
     */
    public Builder setDesc(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      desc_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDesc() {
      desc_ = getDefaultInstance().getDesc();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 2;</code>
     * @param value The bytes for desc to set.
     * @return This builder for chaining.
     */
    public Builder setDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      desc_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<com.secretflow.spec.v1.Div> divs_ =
      java.util.Collections.emptyList();
    private void ensureDivsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        divs_ = new java.util.ArrayList<com.secretflow.spec.v1.Div>(divs_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.Div, com.secretflow.spec.v1.Div.Builder, com.secretflow.spec.v1.DivOrBuilder> divsBuilder_;

    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public java.util.List<com.secretflow.spec.v1.Div> getDivsList() {
      if (divsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(divs_);
      } else {
        return divsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public int getDivsCount() {
      if (divsBuilder_ == null) {
        return divs_.size();
      } else {
        return divsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public com.secretflow.spec.v1.Div getDivs(int index) {
      if (divsBuilder_ == null) {
        return divs_.get(index);
      } else {
        return divsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public Builder setDivs(
        int index, com.secretflow.spec.v1.Div value) {
      if (divsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDivsIsMutable();
        divs_.set(index, value);
        onChanged();
      } else {
        divsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public Builder setDivs(
        int index, com.secretflow.spec.v1.Div.Builder builderForValue) {
      if (divsBuilder_ == null) {
        ensureDivsIsMutable();
        divs_.set(index, builderForValue.build());
        onChanged();
      } else {
        divsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public Builder addDivs(com.secretflow.spec.v1.Div value) {
      if (divsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDivsIsMutable();
        divs_.add(value);
        onChanged();
      } else {
        divsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public Builder addDivs(
        int index, com.secretflow.spec.v1.Div value) {
      if (divsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDivsIsMutable();
        divs_.add(index, value);
        onChanged();
      } else {
        divsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public Builder addDivs(
        com.secretflow.spec.v1.Div.Builder builderForValue) {
      if (divsBuilder_ == null) {
        ensureDivsIsMutable();
        divs_.add(builderForValue.build());
        onChanged();
      } else {
        divsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public Builder addDivs(
        int index, com.secretflow.spec.v1.Div.Builder builderForValue) {
      if (divsBuilder_ == null) {
        ensureDivsIsMutable();
        divs_.add(index, builderForValue.build());
        onChanged();
      } else {
        divsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public Builder addAllDivs(
        java.lang.Iterable<? extends com.secretflow.spec.v1.Div> values) {
      if (divsBuilder_ == null) {
        ensureDivsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, divs_);
        onChanged();
      } else {
        divsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public Builder clearDivs() {
      if (divsBuilder_ == null) {
        divs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        divsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public Builder removeDivs(int index) {
      if (divsBuilder_ == null) {
        ensureDivsIsMutable();
        divs_.remove(index);
        onChanged();
      } else {
        divsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public com.secretflow.spec.v1.Div.Builder getDivsBuilder(
        int index) {
      return getDivsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public com.secretflow.spec.v1.DivOrBuilder getDivsOrBuilder(
        int index) {
      if (divsBuilder_ == null) {
        return divs_.get(index);  } else {
        return divsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public java.util.List<? extends com.secretflow.spec.v1.DivOrBuilder> 
         getDivsOrBuilderList() {
      if (divsBuilder_ != null) {
        return divsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(divs_);
      }
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public com.secretflow.spec.v1.Div.Builder addDivsBuilder() {
      return getDivsFieldBuilder().addBuilder(
          com.secretflow.spec.v1.Div.getDefaultInstance());
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public com.secretflow.spec.v1.Div.Builder addDivsBuilder(
        int index) {
      return getDivsFieldBuilder().addBuilder(
          index, com.secretflow.spec.v1.Div.getDefaultInstance());
    }
    /**
     * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
     */
    public java.util.List<com.secretflow.spec.v1.Div.Builder> 
         getDivsBuilderList() {
      return getDivsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.secretflow.spec.v1.Div, com.secretflow.spec.v1.Div.Builder, com.secretflow.spec.v1.DivOrBuilder> 
        getDivsFieldBuilder() {
      if (divsBuilder_ == null) {
        divsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.secretflow.spec.v1.Div, com.secretflow.spec.v1.Div.Builder, com.secretflow.spec.v1.DivOrBuilder>(
                divs_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        divs_ = null;
      }
      return divsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:secretflow.spec.v1.Tab)
  }

  // @@protoc_insertion_point(class_scope:secretflow.spec.v1.Tab)
  private static final com.secretflow.spec.v1.Tab DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.secretflow.spec.v1.Tab();
  }

  public static com.secretflow.spec.v1.Tab getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Tab>
      PARSER = new com.google.protobuf.AbstractParser<Tab>() {
    @java.lang.Override
    public Tab parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Tab> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Tab> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.secretflow.spec.v1.Tab getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

