// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secretflow/spec/v1/report.proto

package com.secretflow.spec.v1;

public interface TabOrBuilder extends
    // @@protoc_insertion_point(interface_extends:secretflow.spec.v1.Tab)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of the Tab.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Name of the Tab.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string desc = 2;</code>
   * @return The desc.
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 2;</code>
   * @return The bytes for desc.
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
   */
  java.util.List<com.secretflow.spec.v1.Div> 
      getDivsList();
  /**
   * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
   */
  com.secretflow.spec.v1.Div getDivs(int index);
  /**
   * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
   */
  int getDivsCount();
  /**
   * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
   */
  java.util.List<? extends com.secretflow.spec.v1.DivOrBuilder> 
      getDivsOrBuilderList();
  /**
   * <code>repeated .secretflow.spec.v1.Div divs = 3;</code>
   */
  com.secretflow.spec.v1.DivOrBuilder getDivsOrBuilder(
      int index);
}
